const word = document.querySelector('.word'),
  btnPrew = document.querySelector('.prew'),
  btnNext = document.querySelector('.next'),
  [...category] = document.querySelectorAll('.category'),
  [...activeLi] = document.querySelectorAll('li'),
  onOff = document.querySelector('.onOff'),
  outputWindow = document.querySelector('.outputWindow'),
  auto = document.querySelector('.auto'),
  stopAuto = document.querySelector('.stopAuto'),
  randomWord = document.querySelector('.randomWord')


const personal = [
"Мистер, господин (не культурно, часто пренебрежительно)", "Mister ['mɪstə] ", 
"Дама (обращение)", "Lady ['leɪdɪ] ", 
"Господин, джентльмен", "Gentleman (gentlemen)", 
"Мэм (обращение)", "Madam (чаще – ma’am)  ['mædəm (mæm)]", 
"Мисс (обращение к незамужней даме)", "Miss", 
"Миссис (обращение к замужней даме), также стоит перед фамилией замужней дамы", "Missis (Mrs) ['mɪsɪz]", 
"Обращение к даме, если не известно, замужем ли, дабы её не обидеть", "Ms [mɪz]", 
"Имя и фамилия", "Name", 
"Имя", "First name ", 
"Фамилия", "Last name/ surname / family name", 
"Возраст", "Age ", 
"Малыш, младенец", "Baby ", 
"Подросток", "Teenager / adolescent ", 
"Ребенок (нейтр.)", "Child ", 
"Взрослый", "Adult  ['ædʌlt] ", 
"Старый", "Old ", 
"Сколько Вам лет?", 
"How old are you? ", 
"Мне ... .(25)", "I am … (25) ", 
"Замужем", "Married ['mærɪd] ", 
"В разводе", "Divorced  [dɪ'vɔ:st] ", 
"Не замужем/ холост/ не встречается", "Single", 
"Овдовевший", "Widowed ['wɪdəud] ", 
"Ребенок (разг. Неформ.)", "Kid ", 
"Ребенок (сленг) (только при обращении к своему чаду)", "Kiddo 	[ʹkıdəʋ]", 
"Маленький ребенок (начинающий ходить)", "Toddler 	['tɔdlə]", 
"Ребенок, отродье (пренебрежительно)", "Brat 	[bræt]", 
"Личность", "Personality 	[pə:sə'nælɪtɪ]", 
"Известная личность, поп-звезда", "Celebrity / pop star	[sɪ'lebrɪtɪ] / [pɔp sta:]", 
"Предки, родня", "Folks 	[fəuks]", 
"20-24", "Early twenties 	['ə:lɪ-'twentɪz]", 
"24-26", "Mid- twenties 	[mɪd-'twentɪz] ", 
"25-29", "Late twenties 	[leɪt-'twentɪz] ", 
"Мне примерно ...", "I am about … 	[aɪ æm ə'baut...]", 
"40+", "Middle-aged	['mɪdəl-eɪdʒd]", 
"На пенсии", "Retired 	[rɪ'taɪəd] ", 
"Пожилой", "Elderly 	['eldəlɪ] ", 
"В 19 лет / в возрасте 19 лет", "At 19 / at the age of 19 	[æt 19 / æt ðə eɪdʒ əv19]", 
"Семейное положение", "Marital / family status 	['mærɪtəl / 'fæmɪlɪ 'steɪtəs]", 
"Пол", "Gender / sex 	['dʒendə / seks]", 
"Контактные данные", "Contact information 	['kɒntækt ˌɪnfə'meɪʃ(ə)n]", 
"Мобильный (сотовый)", "Mobile / cell number 	['məubaɪl / sel 'nʌmbə]", 
"Номер", "Number	['nʌmbə]", 
"Домашний номер", "Home number 	[həʊm 'nʌmbə]", 
"Рабочий номер", "Work (office) number	[wə:k ('ɒfɪs) 'nʌmbə]", 
"Адрес", "Address 	[ə'dress]", 
"Какой у Вас номер телефона?", "What is your phone number? 	[wɒt ɪz jɔ:(r) fəʊn 'nʌmbə]", 
"Какой у Вас адрес?", "What is your address? 	[wɒt ɪz jɔ:(r) ə'dress]"
]

const character = [
"Голодный", "Hungry ['hʌŋgrɪ]", 
"Большой", "Big	[bɪg]", 
"Большой / крупный", "Large	[lɑːʤ]", 
"Маленький", "Little / small	['lɪtl] / [smɔːl]", 
"Горячий", "Hot	[hɔt]", 
"Занятой", "Busy	['bɪzɪ]", 
"Помешанный (на чем-л.)", "Crazy (about)	['kreɪzɪ]", 
"Настоящий", "Real	[rɪəl]", 
"Строгий", "Strict	[strɪkt]", 
"Настоящий", "True	[truː]", 
"Реалист", "Realist	[ˈrɪəlɪst]", 
"Патриотичный", "Patriotic	[ˌpætrɪ'ɔtɪk]", 
"Импульсивный", "Impulsive	[ɪm'pʌlsɪv]", 
"Взволнованный", "Excited	[ɪk'saɪtɪd]", 
"Ревнивый", "Jealous	['ʤeləs]", 
"Наивный", "Naive	[naɪˈiːv]", 
"Пассивный", "Passive	[ˈpæsɪv]", 
"Странный, чудной", "Weird	[wɪəd]", 
"Коварный, хитрый", "Sly	[slaɪ]", 
"Непосредственный", "Spontaneous	[spɔn'teɪnɪəs]", 
"Непредсказуемый", "Unpredictable	[ˌʌnprɪ'dɪktəbl]", 
"Необычный", "Unusual / uncommon	[ʌn'juːʒ(ə)l] / [ʌn'kɔmən]", 
"Черта характера", "Character trait	[ˈkærɪktə(r) treɪt]", 
"Скрупулезный", "Accurate	['ækjərət]", 
"Ужасный (крутой)", "Awesome	['ɔːsəm]", 
"Испытывающий скуку", "Bored	[bɔːd]", 
"Капризный, нетерпеливый", "Capricious / fretful / impatient	[kə'prɪʃəs] / ['fretf(ə)l] / [ɪm'peɪʃ(ə)nt]", 
"Необщительный", "Unsociable	[ʌn'səuʃəbl]", 
"Хитрый, лукавый, коварный; пронырливый", "Cunning	['kʌnɪŋ]", 
"Эксцентричный", "Eccentric	[ɪk'sentrɪk]", 
"Беспечный", "Light-hearted / easy-going	[ˌlaɪtˈhɑːtɪd] / [i:zi:gəuiŋ]", 
"Замкнутый", "Reserved	[rɪ'zɜːvd]", 
"Задумчивый", "Thoughtful	[θɔːtf(ə)l]", 
"Непринужденный, раскованный", "Relaxed	[rıʹlækst]", 
"Меланхоличный", "	Melancholic	[ˌmelən'kɔlɪk]", 
"Обыкновенный", "Ordinary / average	['ɔːd(ə)n(ə)rɪ] / ['æv(ə)rɪʤ]", 
"Жесткий, суровый", "Tough	[tʌf]", 
"Позитивные черты характера", "Positive traits", 
"Дружелюбный	Friendly	['frendlɪ]", 
"Умный", "Clever	[ˈklevə(r)]", 
"Умный", "Smart	[smɑːt]", 
"Умный, разумный", "Intelligent	[ɪnˈtelɪdʒənt]", 
"Красивый", "Beautiful	['bjuːtɪf(ə)l]", 
"Хороший", "Good	[gud]", 
"Серьезный", "Serious	[ˈsɪərɪəs]", 
"Счастливый", "Happy	['hæpɪ]", 
"Честный", "Honest	['ɔnɪst]", 
"Идеальный", "Ideal / perfect	[aɪˈdiːəl] / ['pɜːfɪkt]", 
"Важный", "Important	[ɪm'pɔːt(ə)nt]", 
"Добрый", "Kind	[kaɪnd]", 
"Позитивный", "Positive	[ˈpɒzɪtɪv]", 
"Терпеливый", "Patient	[ˈpeɪʃ(ə)nt]", 
"Организованный", "Organized	['ɔːg(ə)naɪzd]", 
"Активный", "Active	[ˈæktiv]", 
"Мудрый, рассудительный", "Wise	[waɪz]", 
"Общительный", "Sociable	['səuʃəb(ə)l]", 
"Веселый", "Cheerful / bright	['ʧɪəf(ə)l] / [braɪt]", 
"Оптимист", "Optimist	[ˈɒptɪmɪst]", 
"Внимательный, заботливый", "Attentive	[ə'tentɪv]",
"Чуткий, чувствительный", "Sensitive	['sen(t)sɪtɪv]", 
"Трудолюбивый", "Hard-working	['hɑːdˌwɜːkɪŋ]", 
"Прекрасный", "Wonderful	['wʌndəf(ə)l]", 
"Ответственный", "Responsible	[rɪˈspɒnsɪb(ə)l]", 
"Независимый", "Independent	[ˌɪndɪ'pendənt]", 
"Привлекательный", "Attractive	[ə'træktɪv]", 
"Справедливый", "Fair 	[feər]", 
"Амбициозный, честолюбивый", "Ambitious	[æm'bɪʃəs]", 
"Смелый", "Brave	[breɪv]", 
"Квалифицированный", "Efficient	[ɪ'fɪʃ(ə)nt]", 
"Заботливый, проявляющий заботу", "Careful	['keəf(ə)l]", 
"Тихий, спокойный", "Calm	[kɑːm]", 
"Гордый; обладающий чувством собственного достоинства", "Proud	[praud]", 
"Активный, энергичный", "Energetic	[ˌenə'ʤetɪk]", 
"Чудный", "Lovely	['lʌvlɪ]", 
"Веселый", "Merry	['merɪ]", 
"Скромный", "Modest	[ˈmɒdɪst]", 
"Талантливый", "Talented	['tæləntɪd]", 
"Гениальный", "Genius	['ʤiːnɪəs]", 
"Застенчивый", "Shy	[ʃaɪ]", 
"Надежный, верный", "Reliable	[rɪˈlaɪəbəl]", 
"Толерантный", "Tolerant	[ˈtɒlərənt]", 
"Зрелый", "Mature	[mə'tjuə]", 
"Здравомыслящий; разумный", "Sensible	['sen(t)sɪb(ə)l]", 
"Застенчивый, робкий, скромный", "Bashful	['bæʃf(ə)l]", 
"С широкими взглядами, с широким кругозором", "Broad-minded	[ˌbrɔːd'maɪndɪd]", 
"Очаровательный", "Charming	['ʧɑːmɪŋ]", 
"Уверенный в себе", "Confident	['kɔnfɪd(ə)nt]", 
"Верный, преданный", "Loyal	['lɔɪəl]",
"Любопытный", "Curious	[ˈkjʊərɪəs]", 
"Забавный", "Humorous / amusing	['hjuːm(ə)rəs] / [ə'mjuːzɪŋ]", 
"Решительный, непоколебимый, стойкий", "Determined	[dɪ'tɜːmɪnd]", 
"Дисциплинированный", "Disciplined	['dɪsəplɪnd]", 
"Бережливый, расчетливый", "Economical	[ˌiːkə'nɔmɪk(ə)l]", 
"Восторженный; полный энтузиазма", "Enthusiastic	[ɪnˌθjuːzɪ'æstɪk]", 
"Великолепный", "Excellent	['eks(ə)l(ə)nt]", 
"Очаровательный", "Fascinating	['fæsɪneɪtɪŋ]", 
"Великодушный, щедрый", "Generous ['ʤen(ə)rəs]", 
"Одаренный", "Gifted	['gɪftɪd]", 
"Гуманный", "Humane	[hjuːˈmeɪn]", 
"Довольный", "Pleased	[pliːzd]", 
"Благоразумный", "Reasonable	['riːz(ə)nəb(ə)l]", 
"Волевой", "Strong-willed	[stroŋ- wild]", 
"Понимающий, отзывчивый", "Understanding	[ˌʌndə'stændɪŋ]", 
"Остроумный	Witty	[ˈwɪtɪ]", 
"Негативный черты характера", "Negative traits", 
"Плохой", "Bad	[bæd]", 
"Холодный", "Cold	[kəuld]", 
"Глупый", "Silly	['sɪlɪ]", 
"Злой", "Angry	[ˈæŋɡrɪ]", 
"Ленивый", "Lazy	[leɪzɪ]",
"Скучный", "Boring / dull	['bɔːrɪŋ] / [dʌl]", 
"Жадный", "Greedy	[ˈɡriːdɪ]", 
"Эгоистичный", "Selfish	['selfɪʃ]", 
"Глупый, тупой; скучный", "Stupid / dull	[ˈstjuːpɪd] / [dʌl]", 
"Ужасный", "Terrible	['terəb(ə)l]", 
"Агрессивный, пробивной, настойчивый", "Aggressive	[ə'gresɪv]", 
"Уродливый", "Ugly	['ʌglɪ]", 
"Нервный", "Nervous	['nɜːvəs]", 
"Расстроенный", "Upset	[ʌp'set]", 
"Жестокий", "Cruel	[ˈkruːəl]", 
"Ужасный", "Horrible	['hɔrəb(ə)l]", 
"Унылый, угрюмый", "Moody	['muːdɪ]", 
"Мерзкий", "Nasty	['nɑːstɪ]", 
"Пессимист", "Pessimist	[ˈpesɪmɪst]", 
"Циничный", "Cynical	[ˈsɪnɪkəl]", 
"Зависимый (от)", "Dependent (on)	[dɪ'pendənt]", 
"Отвратительный", "Disgusting	[dɪs'gʌstɪŋ]", 
"Завистливый", "Envious	['envɪəs]", 
"Глупый; взбалмошный", "Foolish	['fuːlɪʃ]"
]

const profession = [
  "Управление", "Management	['mænɪʤmənt]",
  "Президент", "President	['prezɪd(ə)nt]",
  "Вице-президент", "Vice-president", "[ˌvaɪs'prezɪd(ə)nt]",
  "Ответственное должностное лицо (исполнительное)", "Executive officer (CEO)	[ɪg'zekjutɪv  'ɔfɪsə] ([ˈsiːiːəʊ])",
  "Директор, член совета директоров", "Director	[dɪ'rektə], [daɪ-]",
  "Директор-распорядитель, управляющий / финансовый директор / маркетинговый директор", "Managing / financial / marketing director	 ['mænɪʤɪŋ] / [faɪ'nænʃ(ə)l] / ['mɑːkɪtɪŋ] [dɪ'rektə]",
  "Заместитель управляющего", "Deputy	['depjutɪ]",
  "Генеральный управляющий; директор предприятия", "General manager	['ʤen(ə)r(ə)l 'mænɪʤə]",
  "Помощник заведующего", "Assistant manager	[ə'sɪst(ə)nt 'mænɪʤə]",
  "Начальник отдела кадров", "Personnel manager	[ˌpɜːs(ə)'nel 'mænɪʤə]",
  "Руководитель производства", "Production manager	[prə'dʌkʃ(ə)n 'mænɪʤə]",
  "Менеджер по маркетингу", "Marketing manager	['mɑːkɪtɪŋ 'mænɪʤə]",
  "Агент по сбыту", "Sales manager	[seɪlz 'mænɪʤə]",
  "Руководитель проекта", "Project  manager	['prɔʤekt 'mænɪʤə]",
  "Надсмотрщик, надзиратель; контролёр, смотритель", "Supervisor	['s(j)uːpəvaɪzə]",
  "Инспектор, ревизор", "Inspector	[ɪn'spektə]",
  "Офис", "Office	['ɔfɪs]",
  "Конторщик, заведующий канцелярии", "Office clerk	['ɔfɪs klɑːk ]",
  "Секретарь (в учреждении)", "Receptionist	[rɪ'sepʃ(ə)nɪst]",
  "Секретарь, помощник", "Secretary	['sekrət(ə)rɪ]",
  "Банк	Bank", "	[bæŋk]",
  "Банкир", "	Banker	['bæŋkə]",
  "Банковский служащий", "Bank officer	[bæŋk 'ɔfɪsə]",
  "Бухгалтер", "Accountant/ bookkeeper	[ə'kauntənt]/ ['bukˌkiːpə]",
  "Экономист", "Economist	[ɪ'kɔnəmɪst]",
  "Кассир", "Cashier	[kæ'ʃɪə]",
  "Аудитор, бухгалтер-ревизор", "Auditor	['ɔːdɪtə]",
  "Продажи и Магазины", "Sales & Stores	[seɪlz] & [stɔːz]",
  "Торговый представитель", "Sales representative	[seɪlz reprɪ'zentətɪv]",
  "Продавец, торговец", "Salesperson/salesman/ saleswoman/seller	['seɪlzˌpɜːs(ə)n]/ ['seɪlzmən]/ ['seɪlzˌwumən]/ ['selə]",
  "Покупатель", "Buyer	['baɪə]",
  "Творческая работа", "Art & Creative work	[ɑːt] & [krɪ'eɪtɪv wɜːk]",
  "Музыкант", "Musician	[mjuː'zɪʃ(ə)n]",
  "Композитор", "Composer	[kəm'pəuzə]",
  "Певец", "Singer	['sɪŋə]",
  "Танцор", "Dancer	['dɑːn(t)sə]",
  "Художник", "Artist	['ɑːtɪst]",
  "Художник/маляр", "Painter	['peɪntə]",
  "Скульптор", "Sculptor	['skʌlptə]",
  "Архитектор", "Architect	['ɑːkɪtekt]",
  "Режиссёр", "Film director	[fɪlm dɪ'rektə]",
  "Продюсер", "Producer	[prə'djuːsə]",
  "Художественный директор", "Art director	[ɑːt dɪ'rektə]",
  "Актёр/актриса", "Actor/actress	['æktə] / ['æktrəs]",
  "Оператор/фотограф", "Cameraman	['kæm(ə)rəmæn]",
  "Журналист", "Journalist	['ʤɜːn(ə)lɪst]",
  "Репортёр", "Reporter	[rɪ'pɔːtə]",
  "Корреспондент", "Correspondent	[ˌkɔrɪ'spɔnd(ə)nt]",
  "Фотограф", "Photographer	[fə'tɔgrəfə]",
  "Школа и Колледж", "School & College	[skuːl] & ['kɔlɪʤ]",
  "Директор (школы)/ ректор (университета)", "Principal	['prɪn(t)səp(ə)l]",
  "Профессор", "Professor	[prə'fesə]",
  "Учитель", "Teacher	['tiːʧə]",
  "Студент Ученик", "Student	['st(j)uːd(ə)nt]",
  "Строительство", "Construction	[kən'strʌkʃ(ə)n]",
  "Инженер", "Engineer	[ˌenʤɪ'nɪə]",
  "Техник", "Technician	[tek'nɪʃ(ə)n]",
  "Механик", "Mechanic	[mɪ'kænɪk]",
  "Строитель", "Builder	['bɪldə]",
  "Рабочий - строитель", "Construction worker	[kən'strʌkʃ(ə)n 'wɜːkə]",
  "Ремонтник", "Repairer	[rɪ'peərə]",
  "Сварщик", "Welder	['weldə]",
  "Каменщик", "Bricklayer	['brɪkˌleɪə]",
  "Плотник/столяр", "Carpenter	['kɑːp(ə)ntə]",
  "Водопроводчик", "Plumber	['plʌmə]",
  "Наука", "Science	['saɪən(t)s]",
  "Учёный", "Scientist	['saɪəntɪst]",
  "Исследователь, научный работник", "Researcher, explorer	[rɪ'sɜːʧə], [ɪk'splɔːrə]",
  "Математик", "Mathematician	[ˌmæθ(ə)mə'tɪʃ(ə)n]",
  "Физик", "Physicist	['fɪzɪsɪst]",
  "Астроном", "Astronomer	[ə'strɔnəmə]",
  "Археолог", "Archaeologist	[ˌɑːkɪ'ɔləʤɪst]",
  "Психоло", "	Psychologist	[saɪ'kɔləʤɪst]",
  "Закон и Порядок", "Law and Order	[lɔː] & ['ɔːdə]",
  "Судья", "Judge	['ʤʌʤ]",
  "Адвокат / юрист", "Lawyer	['lɔɪə], ['lɔːjə] / [ə'təːnɪ]",
  "Полицейский", "Police officer, policeman	[pə'liːs 'ɔfɪsə], [pə'liːsmən]",
  "Сотрудник дорожной полиции", "Traffic officer	['træfɪk 'ɔfɪsə]",
  "Другое", "Other	['ʌðə]",
  "Водитель", "Driver	['draɪvə]",
  "Пилот", "Pilot	['paɪlət]",
  "Программист", "Computer programmer / operator	[kəm'pjuːtə 'prəugræmə] / ['ɔp(ə)reɪtə]",
  "Специалист", "Specialist	['speʃ(ə)lɪst]",
  "Автомеханик", "Car mechanic	[ka: mɪ'kænɪk]",
  "Аналитик", "Analyst	['æn(ə)lɪst]",
  "Библиотекарь", "Librarian	[laɪ'breərɪən]",
  "Веб-мастер", "	Webmaster	[web 'mɑːstə]",
  "Веб-разработчик", "Web developer	[web dɪ'veləpə]",
  "Консультант", "Consultant	[kən'sʌlt(ə)nt]",
  "Модель", "Model	['mɔd(ə)l]",
  "Парикмахер", "Hairdresser	['heəˌdresə]",
  "Парикмахер (мужской)", "Barber	['bɑːbə]",
  "Пожарный", "Fire-fighter	['faɪəˌfaɪtə]",
  "Политик", "Politician	[ˌpɔlɪ'tɪʃ(ə)n]",
  "Портной", "Tailor	['teɪlə]",
  "Священник", "Priest	[priːst]",
  "Специалист программного обеспечения", "Software specialist	['sɔftweə 'speʃ(ə)lɪst]",
  "Уборщик, Дворник", " 	Janitor	['ʤænɪtə]",
  "Уборщица", "Cleaning lady / woman	['kliːnɪŋ 'leɪdɪ]/ ['wumən]",
  "Фермер", "Farmer	['fɑːmə]",
  "Эксперт, мастер", "Expert	['ekspɜːt]",
]

const body = [
  "Голова", "Head	[ hed ]",
  "Волосы", "	Hair	[ hɛə ]",
  "Глаз", "Eye	[ ai ]",
  "Губы", "Lips	[ lips ]",
  "Зуб (зубы)", "Tooth (teeth)[ tu:θ ] ([tiːθ])",
  "Лицо", "Face	[ feis ]",
  "Нос", "Nose	[ nəuz ]",
  "Рот", "Mouth	[ mauθ ]",
  "Ухо", "Ear	[ iə ]",
  "Язык", "Tongue	[ tʌŋ ]",
  "Конечности", "Limbs / extremities	[lɪmz] / [ɪk'stremətɪz]",
  "Рука (от плеча до кисти)", "Arm	[ ɑ:m ]",
  "Кисть руки", "Hand	[ hænd ]",
  "Палец руки", "Finger[fɪŋɡə(r) ]",
  "Ладонь", "Palm	[ pɑ:m ]",
  "Плечо", "Shoulder	[ 'ʃəuldə ]",
  "Нога(до ступни)", "Leg	[ leg ]",
  "Нога (ступня)/ ноги (ступни)", "Foot / feet	[ fut ] / [ fi:t ]",
  "Тело", "Body	['bɔdɪ]",
  "Грудь", "Breast	[ brest ]",
  "Живот(желудок)", "Stomach	[ 'stʌmək ]",
  "Живот", "Belly 	[ˈbɛlɪ]",
  "Спина", "Back	[ bæk ]",
  "Талия", "Waist	[ weist ]",
  "Шея", "Neck	[ nek ]",
  "Ягодицы", "Buttocks 	[‘bʌtəks]",
  "Тело", "Body	['bɔdɪ]",
  "Хорошо сложенный (о мужчине)", "Well-built	[ˌwel'bɪlt]",
  "С хорошей фигурой (о женщине)", "Well-shaped	[‘welʃeɪpt]",
  "Худой, тощий", "Skinny / slender / thin / emaciated / frail	[‘skɪnɪ / 'slendə / θɪn / ɪ'meɪʃɪeɪtɪd / freɪl]",
  "Толстый, полный", "Overweight / plump (polite)/ stout (polite)/ thick / obese (impolite)/ large (neutral)/ chubby (little bit overweight, polite)	[əuvə’weɪt / plʌmp/ staut/ θɪk / əu'biːs/ lɑːʤ / ‘tʃʌbɪ]",
  "Низкий", "Short 	[ʃɔ:t ]",
  "Высокий", "Tall	[tɔ:l]",
  "Среднего роста", "Medium height	[‘mi:dɪəm haɪt]",
  "Волосы", "Hair	[heə]",
  "Лысый", "Bald /  bald-headed	[bɔ:ld] / ['bɔːld'hedɪd]",
  "Прямые", "Straight	[streɪt]",
  "Волнистые", "Wavy	[‘weɪvɪ]",
  "Кудрявые", "Curly	['kɜːlɪ]",
  "Седые(с проседью)", "Gray	[greɪ]",
  "Седые (полностью)", "White	[wait]",
  "Блондинистые", "Blond	[blɔnd]",
  "Рыжие", "Ginger / red	['ʤɪnʤə] / [red]",
  "Волосы средней длины, до плеч", "Shoulder-length	[ˌʃəuldə'leŋθ]",
  "Косы", "Braids / plaits	[breɪdz] / [plæts] ",
  "Локон, завиток", "Lock / curl / ringlet	[lɔk] / [kɜːl] / ['rɪŋlɪt]",
  "Челка", "Fringe / bangs	[frɪnʤ] / [bæŋz]",
  "Стрижка", "Haircut	[‘hɛəkʌt]",
  "Причёска", "Hairdo	[‘hɛədu:]",
  "Перманентная", "завивка	Perm	[pə:m]",
  "Жидкие волосы", "Sparse hair	[spɑ:s heə]",
  "Редкие", "Scanty / thin	['skæntɪ] / [θɪn]",
  "Густые", "Thick 	[θɪk]",
  "Шелковистые", "Silky	['sɪlkɪ]",
  "Крашеные", "Dyed 	[daɪd]",
  "Лицо", "Face	[feɪs]",
  "Бледная кожа", "Pale skin	[peɪl skɪn]",
  "Загорелый", "Sun-tanned	[sʌn- tænd]",
  "Морщины", "Wrinkles	[‘rɪŋklz]",
  "Родинка", "Mole	[məul]",
  "Квадратное / круглое / овальное (лицо)", "Square / round / oval	[skweə /  raund /  'əuv(ə)l]",
  "Впалые щеки", "Hollow cheeks  	['hɔləu tʃi:ks]",
  "Пухлое лицо", "Chubby face  	[‘tʃʌbɪ feɪs]",
  "Гладко выбритый", "Clean-shaven / smooth-cheeked  	[ˌkliːn'ʃeɪv(ə)n] / [smuːð ʧiːkt]",
  "Высокие скулы", "High cheekbones  	[haɪ ‘tʃi:kbəunz]",
  "Круговая пластика", "Face lift  	[feɪs lɪft]",
  "Веснушки", "Freckles	['freklz]",
  "Ямочки", "Dimples	[‘dɪmplz]",
  "Угри", "Acne	[ʹæknı]",
  "Шрам", "Scar	[skɑ:]",
  "Оттопыренные уши", "Prominent ears	['prɔmɪnənt ɪəz]",
  "Бородавкa", "Wart	[wɔ:t]",
  "Мочка уха", "Ear lobe	[ ɪə ləub]",
  "Прыщ", "Spot / pimple	[spɔt] / [‘pɪmpl]",
  "Улыбка", "Smile	[smaɪl]",
  "Глаза", "Eyes	[aɪz]",
  "Синяк под глазом", "Black eye  	[blæk aɪ]",
  "Толстые / тонкие брови", "Thick / thin eyebrows	[θɪk] / [θɪn 'aɪbrauz]",
  "Длинные ресницы", "	Long lashes  	[lɔŋ læʃɪz]",
  "Накладные ресницы", "False eyelashes   	[fɔ:ls ailæʃɪs]",
  "Широко посаженные", "Wide-set	[waɪd set]",
  "Раскосые/миндалевидные глаза", "Slanting / almond-shaped eyes	['slɑːntɪŋ] / [ 'ɑːmənd‘ʃeɪpt aɪz]",
  "Косоглазый", "Cross eyed 	[krɔs aɪd]",
  "Поросячьи глазки", "Piggy eyes  	[‘pɪgɪ aɪz]",
  "Косматые", "Shaggy 	['ʃægɪ]",
  "Густые", "Bushy	['buʃɪ]",
  "Губы", "Lips	[lɪps]",
  "Полные / тонкие губы", "Full / thin lips	[ful] / [θɪn lɪps]",
  "Верхняя / нижняя губа", "Upper / lower lip	 ['ʌpə] / ['ləuə lɪp]",
  "Кусать губы", "To bite one's lips	[baɪt <one's> lɪps]",
  "Поджать губы", "To purse  one's lips	[pɜːs <one's> lɪps]",
  "Презрительно кривить губы", "To curl one's lips	[kɜːl <one's> lɪps]",
  "Нос", "Nose	[nəuz]",
  "Вздёрнутый", "Upturned	[‘ʌptə:nd]",
  "Мясистый", "Fleshy 	['fleʃɪ]",
  "Изогнутый, кривой", "Crooked	['krukɪd]",
  "Крючковатый", "Hooked	[hukt]",
  "Кривой", "Curved 	['kɜːvd]",
  "Приплюснутый нос", "Pug nose  	[pʌg nəuz]",
  "Нос картошкой", "Bulbous nose  	[‘bʌlbəs nəuz]",
  "Курносый нос", "Snub nose  	[snʌb nəuz]",
  "Подбородок", "Chin	[ʧɪn]",
  "Двойной", "Double 	[‘dʌbl]",
  "Острый", "Pointed	[’pɔɪntɪd]",
  "Массивный", "Massive 	['mæsɪv]",
  "Выдающийся", "Protruding 	[prə'truːdɪŋ]",
  "Круглый", "Round 	[raʊnd]",
  "Зубы", "Teeth	[tiːθ]",
  "Белоснежные зубы", "Snow-white teeth	[‘snəʊ’waɪt ti:θ]",
  "Крупные", "Large 	[lɑːʤ] ",
  "Мелкие", "Small / tiny	[smɔːl] / ['taɪnɪ]",
  "Редкие", "Widely-spaced	['waɪdlɪ speıst]",
  "Ровные / неровные", "Even / uneven 	[ʌn'iːv(ə)n] / [ʌn'iːv(ə)n]",
  "Вставные зубы", "False teeth  	[fɔ:ls ti:θ]",
  "Квадратная челюсть", "Square jaw	[skweə ʤɔː]"
]

const clothes = [
  "Верхняя одежда", "Outwear	[ˌaut'weə]",
  "Пальто, плащ", "	Сoat	[kəʊt]",
  "Плащ", "	Raincoat	['reɪnkəut]",
  "Куртка", "	Jacket	[‘dʒækɪt]",
  "Спортивная куртка", "	Sport jacket	[spɔ:t ‘dʒækɪt]",
  "Шуба", "	Fur coat	[fɜː kəut]",
  "Пуховик", "	Down jacket 	[daun ‘dʒækɪt]",
  "Дублёнка", "	Sheepskin coat 	['ʃiːpskɪn kəut]",
  "Зимнее пальто", "	Winter coat	[‘wɪntə kəut]",
  "Головные уборы", "		Headwear	['hedgɪə]",
  "Шапка, шляпа", "	Hat 	[hæt]",
  "Кепка", "	Cap	[kæp]",
  "Берет", "	Beret	['bereɪ]",
  "Панама	", "Sun hat	[sʌn hæt]",
  "Шерстяная шапка", "	Woollen hat	['wulən hæt]",
  "Верхняя часть тела", "	Upper body	['ʌpə  'bɔdɪ]",
  "Рубашка", "	Shirt	[ʃ3:t]",
  "Футболка", "	T-shirt  	[ti: - ʃ3:t]",
  "Свитер, джемпер", "	Jumper	[‘dʒʌmpə]",
  "Свитер", "	Sweater	[‘swetəʳ]",
  "Блузка", "	Blouse 	[blaʊz]",
  "Туника", "	Tunic	['tjuːnɪk]",
  "Пуловер", "	Pullover	['puləuvə]",
  "Кардиган", "	Cardigan	['kɑ:dɪgən] ",
  "Топ", "	Top 	[tɔp]",
  "Жилетка", "	Waistcoat, vest (am.) 	['weɪstkəut] , [vɛst]",
  "Майка", "	Undervest  	[‘ʌndəvɛst]",
  "Нижняя часть тела", "Lower body	['ləuə 'bɔdɪ]",
  "Брюки", "Trousers (br.), pants (am.)	[‘traʊzɪz], [pænts]",
  "Носки", "Socks	[sɔks]",
  "Юбка", "Skirt 	[sk3:t]",
  "Шорты", "Shorts 	[‘ʃɔ:ts]",
  "Колготки", "Tights, panty hose (am.)	[taɪts], ['pæntɪhəuz]",
  "Джинсы", "Jeans 	[ʤiːnz]",
  "Легинсы", "Leggings	[‘legɪŋz]",
  "Слаксы (широкие брюки)", "Slacks	[slæks]",
  "Гетры", "Leg warmers 	[leg wɔ:məz]",
  "Гольфы", "Knee-high stockings	[ni:'haɪ 'stɔkɪŋz]",
  "Чулки", "Stockings, stay ups 	['stɔkɪŋz], [steɪʌps]",
  "Все тело", "Whole body	[həul 'bɔdɪ]",
  "Платье", "Dress 	[dres]",
  "Костюм", "Suit	[su:t]",
  "Комбинезон", "Overall / coveralls	[‘əʊvərɔ:l] / ['kʌv(ə)rɔːlz]",
  "Брючный костюм", "Trouser suit, slack suit, pantsuit	['trauzə su:t], [slæk su:t], ['pænt s(j)uːt]",
  "Женский костюм (с юбкой)", "Skirt suit	[skɜːt su:t]",
  "Сарафан", "Pinafore dress  sundress	['pɪnəfɔ: dres]",
  "Летнее платье", "Summer dress	['sʌmə dres]",
  "Халат", "Robe 	[rəʊb]",
  "Нижнее бельё", "Underwear	['ʌndəweə]",
  "Бюстгальтер", "Bra 	[brɑ:]",
  "Трусы (мужские)", "Underpants	['ʌndəpænts]",
  "Мужские широкие трусы", "Boxers	['bɔksəz]",
  "Трусики (женские или детские)", "	Panties	['pæntɪz] ",
  "Купальник", "Bikini / swimsuit	[bɪ'kiːnɪ] / [swɪms(j)uːt]",
  "Обувь", "Footwear	['futweə]",
  "Туфли, ботинки", "Shoes 	[ʃu:z]",
  "Ботинки, сапоги", "Boots	[bu:ts]",
  "Туфли на высоком каблуке", "High heels 	[haɪ hi:lz]",
  "Туфли на низком каблуке", "Low heels 	[ləu hi:lz]",
  "Кроссовки", "Trainers (br.), sneakers (am.)	['treɪnəz], ['sni:kəz]",
  "Обувь на низкой подошве", "Flats	[flæts]",
  "Сандалии", "Sandals	[‘sændlz]",
  "Шлёпки", "Flip-flops 	[flɪp- flɔps]",
  "Домашние тапочки", "Slippers	[‘slɪpəz]",
  "Шнурок", "Lace	[leɪs]",
  "Зимние сапоги", "Winter boots	['wɪntə buːts]",
  "Обувь на шпильках", "Stiletto heels	[stɪ'letəu hi:lz]",
  "Подошва", "Sole 	[səul]",
  "Платформа", "Platform sole	['plætfɔːm səul]",
  "Туфли на платформе", "Platform shoes	['plætfɔːm ʃu:z]",
  "Ковбойские сапоги", "Western boots, cowboy boots	['westən buːts], ['kaubɔɪ buːts]",
  "Туристические ботинки", "Hiking boots	['haɪkɪŋ buːts]",
  "Мокасины", "Moccasins	['mɔkəsɪnz]",
  "Тенниски", "Tennis shoes	['tenɪs ʃu:z]",
  "Аксессуары	", "Accessories	[ək'ses(ə)rɪz]",
  "Очки", "Glasses 	[glɑ:sɪz]",
  "Шарф", "Scarf 	[skɑ:f]",
  "Галстук", "Tie	[taɪ]",
  "Кольцо", "Ring	[rɪŋ]",
  "Кошелек", "Purse/ wallet	[pə:s/ ‘wɒlɪt]",
  "Браслет", "Bracelet	['breɪslɪt]",
  "Цепочка", "Chain	[tʃeɪn]",
  "Ожерелье	", "ecklace	[‘neklɪs]",
  "Солнечные очки", "Sunglasses 	[‘sʌnˌglɑ:sɪz]",
  "Серьги", "Pins / earrings 	[pɪnz] / ['ɪərɪŋz]",
  "Женская сумка", "Handbag 	[‘hændbæg]",
  "Драгоценности", "Jewellery	[‘dʒu:əlrɪ]",
  "Бижутерия", "Bijouterie	[bɪ'ʒu:tərɪ]",
  "Обруч, повязка на голову", "Hair-band	[hɛəʳ- bænd]",
  "Сумка-клатч", "Clutch	[klʌtʃ]",
  "Брошь", "Brooch	[brəuʧ]",
  "Пашмина", "Pashmina 	[pæʃ’mi:nə]",
  "Бабочка", "Bow-tie 	[baʊ- taɪ]",
  "Стили", "Styles	[staɪlz]",
  "Короткий / длинный рукав", "Short / long sleeve	[ʃɔ:t / lɔŋ sli:v]",
  "Принт / рисунок на одежде", "Print	[prɪnt]",
  "V вырез", "V-neck	[vi- nek]",
  "Мини / миди / макси- юбка", "Mini / midi / maxi- skirt	[mini / ’mɪdɪ / maksi sk3:t]",
  "Платье со складками", "Pleated dress	[pli:tid dres]",
  "В складку", "Pleated	[pli͟:tɪd]",
  "Круглый вырез", "Round-neck	[raund nek]",
  "Пышная юбка", "Full-skirt	[ful- sk3:t]",
  "Материал", "Fabric	['fæbrɪk]",
  "Хлопок", "Cotton	['kɔt(ə)n]",
  "Джинсовая ткань", "Denim	['denɪm]",
  "Шерсть", "Wool	[wul]",
  "Кожа", "Leather	[‘leðəʳ]",
  "Мех", "Fur	[fə:r]",
  "Шелк", "Silk	[sɪlk]",
  "Бархат", "Velvet	['velvɪt]",
  "Вельвет", "Corduroy	['kɔ:d(j)ərɔɪ] ",
  "Вязанный", "Knitted	['nɪtɪd]",
  "Искусственный мех / кожзам", "Fake fur / leather	[feɪk fə:r/ ’leðəʳ]",
  "Полиэстер", "Polyester	[pɔlɪ’ɛstər]",
  "Цвета", "Colours	['kʌləz]",
  "Красный", "Red	[rɛd]",
  "Оранжевый", "Orange	[‘ɒrɪndʒ]",
  "Желтый", "Yellow 	[‘jeləʊ]",
  "Зеленый", "Green 	[gri:n]",
  "Синий", "Blue	[blu:]",
  "Голубой", "Light blue 	[laɪt blu:]",
  "Черный", "Black	[blæk]",
  "Коричневый", "Brown 	[braʊn]",
  "Белый", "White	[waɪt]",
  "Темно-синий", "Navy	[‘neɪvɪ]",
  "Фиолетовый", "Purple	[‘p3:pl]",
  "Бежевый", "Beige	[beɪʒ]",
  "Действия", "Actions	['ækʃ(ə)nz]",
  "Надевать что-то", "To put smth on	[pʊt <smth> ɒn]",
  "Снимать", "To take smth off 	[teɪk <smth> ɒf]",
  "Носить (одежду, украшения)", "To wear 	[wɛə]",
  "Примерять", "To try on	[ʹtraı ɒn]",
  "Переодеваться", "	To change clothes	[ʧeɪnʤ kləuðz] ",
  "Одеваться", "	To dress, to get dressed	[dress], [get dresst]",
  "Раздеваться", "	To undress, to get undressed	[ʌn'dres], [get ʌn'drest]",
  "Одеваться 'на выход'", "To dress up 	[dres ʌp]",
  "Подходить (о фасоне, размере)", "To fit	[fɪt]",
  "Подходить, быть к лицу", "To suit	[s(j)u:t]",
  "Подходить (детали одежды между собой; по цвету)", "To match 	[mætʃ]",
  "Нарядная одежда", "Smart clothes	[smɑːt kləuðz]",
  "Вечернее платье", "Evening gown	['i:vnɪŋ gaun]",
  "Смокинг", "Tux, tuxedo (am.), dinner jacket (br.)	[tʌks], [tʌk'si:dəu], ['dɪnə 'ʤækɪt]",
  "Спортивная одежда", "Sportswear	['spɔːtsweə]",
  "Тренировочные (штаны)", "	Sweatpants	['swetpænts]",
  "Спортивный костюм", "Tracksuit	['træks(j)uːt]",
  "Домашняя одежда", "Home clothing	[həum 'kləuðɪŋ]",
  "Пижама", "Pyjamas	[pɪ'ʤɑ:məz] ",
  "Халат", "Dressing-gown	['dresɪŋ gaun]",
  "Узор", "Pattern	['pæt(ə)n]",
  "В полоску", "Striped	[straɪpt]",
  "В клеточку", "Checked 	[ʧekt]",
  "Цветастый", "Flowery, floral	['flauərɪ], ['flɔ:r(ə)l]",
  "В горошек", "Polka dot	['pɔlkə dɔt]",
  "Камуфляж", "Camouflage 	['kæməflɑ:ʒ] ",
  "Без рисунка", "Plain	[pleɪn]",
  "Шотландская клетка", "Plaid	[plæd]",
  "Описание	Description", "[dɪ'skrɪpʃ(ə)n] ",
  "Элегантный", "Elegant	['elɪg(ə)nt] ",
  "Повседневный", "Casual	['kæʒwəl]",
  "Плотно облегающий", "Tight 	[taɪt]",
  "Мешковатый", "Baggy	['bægɪ]",
  "Свободный", "Loose	[lu:s] ",
  "Модный", "Fashionable 	['fæʃ(ə)nəb(ə)l] ",
  "Пуговица", "Button	[‘bʌt (ə)n]",
  "Карман", "Pocket	['pɔkɪt]",
  "Воротник", "Collar	[‘kɔlə]",
  "Ремень", "Belt	[belt]",
  "Перчатки", "Gloves	[glʌvz]",
  "Лента", "Ribbon	['rɪb(ə)n]",
  "Капюшон", "Hood	[hud] ",
  "Носовой платок", "Handkerchief	['hæŋkəʧi:f]",
  "Молния", "Zip	[zɪp]"
]

const routine = [
  "Вставать", "To get up	[ ‘ɡet ʌp ]",
  "Мыть руки", "To wash hands 	[ wɒʃ hændz ]",
  "Мыть лицо", "To wash face 	[ wɒʃ feɪs ]",
  "Умываться", "To wash hands & face 	[ wɒʃ hændz & feɪs ]",
  "Чистить зубы", "To clean (brush) teeth 	[ kliːn (brʌʃ) tiːθ ]",
  "Идти в ванную", "To go to the bathroom 	[ ɡəʊ tə ðə ‘bɑːθruːm ]",
  "Принимать душ", "To take a shower	[ teɪk ə ‘ʃaʊə ]",
  "Принимать ванну", "To take a bath 	[ teɪk ə bɑːθ ]",
  "Идти в кухню", "To go to the kitchen 	[ ɡəʊ tə ðə ‘kɪtʃɪn ]",
  "Завтракать/обедать/ужинать", "To have breakfast /  lunch / dinner/supper 	[ həv ‘brekfəst /  lʌntʃ /  ‘dɪnə / ‘sʌpə ]",
  "Уходить / оставлять / покидать", "To leave 	[ li:v ]",
  "Уходить из дома", "To leave home 	[ li:v həʊm ]",
  "Уходить с работы", "To leave work 	[ li:v ‘wɜːk ]",
  "Уходить на работу", "To leave for work 	[ li:v fə ‘wɜːk ]",
  "Уходить из дома на работу", "To leave home for work 	[ li:v həʊm fə ‘wɜ:k ]",
  "Ходить за покупками / делать покупки", "To go shopping / do shopping	[ ɡəʊ ‘ʃɒpɪŋ / du: ‘ʃɒpɪŋ ]",
  "Смотреть ТВ", "To watch TV 	[ wɒtʃ ˌti:’vi: ]",
  "Сидеть в интернете", "To surf the net 	[ sɜ:f ðə net ]",
  "Пользоваться компьютером", "To use a computer 	[ ‘ju:z ə kəm’pju:tə ]",
  "Слушать музыку", "To listen to music	[ ‘lɪsn̩ tə ‘mju:zɪk ]",
  "Ходить в гости к друзьям", " 	To visit friends	[‘vɪzɪt frendz ]",
  "Принимать гостей", "To receive guests	[ri’si:v gests]",
  "Играть в игры / карты", "To play games / cards	[pleɪ ɡeɪmz / kɑ:dz ]",
  "Иметь обеденный перерыв", "To have a lunch break 	[həv ə lʌntʃbreɪk ]",
  "Возвращаться", "To come back / to return 	[ kʌm ‘bæk] / [rɪ’tɜ:n ]",
  "Перед тем, как ложиться спать", "Before going to bed [ bɪ’fɔ: ‘ɡəʊɪŋ tə bed ]",
  "Читать перед сном", "To read before sleeping	[ ri:d bɪ’fɔ: ‘sli:pɪŋ ]",
  "Ложиться спать", "To go to bed 	[ ɡəʊ tə bed ]",
  "Засыпать", "To fall asleep	[ fɔ:l ə’sli:p ]",
  "Стричь газон", "To mow a lawn	[ maʊ ə lɔ:n ]",
  "Копать", "To dig	[ dɪɡ ]",
  "Полоть сорняки", "To pull weeds	[ pʊl wi:dz ]",
  "Поливать", "To water / irrigate	[ ‘wɔ:tə ] / [‘ɪrɪɡeɪt ]",
  "Идти пешком/ прогуливаться", "To go on foot / to walk / to have a stroll	[ɡəʊ ɒn fʊt / wɔ:k / həv ə strəʊl]",
  "Удобрять", "To fatten / nourish	[‘fæt(ə)n̩ / ‘nʌrɪʃ ]",
  "Стирка", "Doing the Laundry	 [ˈduːɪŋ ðə ˈlɔːndri]",
  "Стирать", "To do the washing	[duː ðə ˈwɒʃɪŋ]",
  "Стирать, мыть", "To wash	[wɒʃ]",
  "Бельё, предназначенное для стирки", "Laundry	[ˈlɔːndri]",
  "Гладить", "To iron / do the ironing	[ˈaɪən  / duː ðɪ ˈaɪənɪŋ]",
  "Рассортировать", "To sort out	[sɔːt aʊt]",
  "Стиральный порошок", "Washing powder	[ˈwɒʃɪŋ ˈpaʊdə]",
  "Бак (стиральной машины)", "Tub	[tʌb]",
  "Таз", "Basin	[ˈbeɪsn ]",
  "Домашние обязанности на кухне", "Chores in the Kitchen	 [tʃɔːz in ðə  'kɪtʃɪn]",
  "Готовить", "To cook	[kʊk]",
  "Мыть посуду", "To do the dishes / to wash up	[duː ðə dɪʃɪz ] / [wɒʃ ʌp]",
  "Губка", "Sponge	[spʌndʒ ]",
  "Накрывать на стол", "To lay the table	[leɪ ðə ˈteɪbl]",
  "Ведение домашнего хозяйства", "Housekeeping	[ˈhaʊskiːpɪŋ]",
  "Вести домашнее хозяйство", "To keep house	[kiːp haʊs ]",
  "Вести домашнее хозяйство", "To run the house	[rʌn ðə haʊs ]",
  "Домашние обязанности", "Domestic chores	[dəˈmestɪk tʃɔːz]",
  "Домохозяйка", "Housewife	[ˈhaʊswaɪf ]",
  "Проветривать", "(комнату)	To air (the room)	[eə (ðə ruːm)]",
  "Беспорядок", "Mess	 [mes]",
  "Грязь", "Dirt	[dɜːt]",
  "Грязный", "Dirty	[ˈdɜːti]",
  "Пыль", "Dust	[dʌst ]",
  "Устраивать беспорядок", "To make a mess	[meɪk ə mes]",
  "След ноги", "Footmark	[ˈfʊtmɑːk]",
  "Пятно", "Stain	[steɪn]",
  "Мусор", "	Rubbish	[ˈrʌbɪʃ]",
  "Пролить", "To spill	[spɪl]",
  "Уборка, порядок", "Cleaning	 [ˈkliːnɪŋ ]",
  "Чистить, прибирать; чистый", "To clean	[kliːn ]",
  "Мыть пол", "To clean / wash the floor	[kliːn / wɒʃ ðə flɔː(r) ]",
  "Делать уборку", "To do the cleaning	[duː ðə ˈkliːnɪŋ ]",
  "Выносить мусор", "To take  the garbage(rubbish) out	[teɪk ðə ˈɡɑːbɪdʒ aʊt]",
  "Заправлять кровать", "To make the bed	[meɪk ðə bed]",
  "Метла, веник", "Broom    	[bruːm]",
  "Щётка", "Brush	[brʌʃ]",
  "Вытирать пыль", "To dust	[dʌst] ",
  "Тряпка для вытирания пыли", "Duster	[ˈdʌstə(r) ]",
  "Совок", "Dustpan	[ˈdʌstpæn]",
  "Тереть (щёткой)", "To scrub	[skrʌb]",
  "Очиститель, жидкоемоющее средство", "Cleanser	[ˈklenzə(r)]",
  "Фартук", "Apron	[ˈeɪprən]",
  "Швабра", "Mop / floor-mop 	[mɒp / flɔː mɒp]",
  "Мусорное ведро", "Dustbin	[ˈdʌstbɪn]",
  "Подметать пол", "To sweep the floor	[swiːp  ðə flɔː(r) ]",
  "Пылесосить", "To vacuum	[ˈvækjuəm]",
  "Глаголы состояния", "[Stative verbs]",
  "Любить", "Love	[ lʌv ]",
  "Обожать", "Adore	[ə'dɔː]",
  "Слышать", "Hear	[ hiə ]",
  "Смотреть", "See	[ si: ]",
  "Помнить", "Remember	[ ri'membə ]",
  "Нуждаться", "Need	[ ni:d ]",
  "Ненавидеть", "Hate	[ heit ]",
  "Знать", "Know	[ nəu ]",
  "Чувствовать", "Feel	[ fi:l ]",
  "Смотреть", "Look	[ luk ]",
  "Значить, означать", "Mean	[ mi:n ]",
  "Вообразить", "Imagine	[ imæʤin ]",
  "Принимать", "Accept	[ ək'sept ]",
  "Обещать", "Promise	[ 'prɔmis ]",
  "Признавать", "Recognize	[ 'rekəgnaiz ]",
  "Верить, полагать", "Believe	[ bi'li:v ]",
  "Соглашаться", "Agree	[ ə'gri: ]",
  "Казаться", "Seem	[ si:m ]",
  "Появляться	Appear", "[ ə'piə ]",
  "Заботиться", "(о)	Care (for)	[keə]",
  "Состоять", "Consist	[ kən'sist ]",
  "Содержать", "Contain	[ kən'tein ]",
  "Отрицать", "Deny	[ di'nai ]",
  "Зависеть", "Depend	[ di'pend ]",
  "Сомневаться", "Doubt	[ daut ]",
  "Соответствовать, подходить (одежда)", "Fit	[ fit ]",
  "Впечатлять", "Impress	[ 'impres ]",
  "Включать", "Include	[ in'klu:d ]",
  "Иметь значение", "Matter	[ 'mætə ]",
  "Замечать", "Notice	[ 'nəutis ]",
  "Обладать", "Possess	[ pə'zes ]",
  "Предпочитать", "Prefer	[ pri:fə: ]",
  "Реализовать", "Realise	[ 'riəlaiz ]",
  "Отказывать", "Refuse	[ ri'fju:z ]",
  "Чувствовать", "Sense	[ sens ]",
  "Глаголы", "[Verbs]",
  "Желать	Wish", "[wɪʃ]",
  "Выбирать", "Choose	[tʃuːz]",
  "Создавать", "Create	[krɪˈeɪt]",
  "Надеятся", "Hope	[həʊp]",
  "Ошибаться", "Be mistaken	[ˈbiː mɪˈsteɪkən]",
  "Опаздывать", "Be late	[‘biː leɪt]",
  "Быть занятым", "Be busy	[ˈbiː ˈbɪzɪ]",
  "Обсуждать", "Discuss	[dɪsˈkʌs]",
  "Запрещать", "Forbid	[fəˈbɪd]",
  "Считать", "Consider	[kənˈsɪdə]",
  "Расценивать, рассматривать", "Regard	[rɪˈɡɑːd]",
  "Полагаться", "Rely	[rɪˈlaɪ]",
  "Достигать", "Achieve	[əˈtʃiːv]",
  "Возражать", "Object	[ˈɒbdʒ|ɛkt]",
  "Критиковать", "Critisize	[ˈkrɪtɪsaɪz]",
  "Винить", "Blame	[bleɪm]",
  "Принимать", "Accept	[əkˈsɛpt]",
  "Притворятся", "Pretend	[prɪˈtɛnd]",
  "Быть в курсе, осведомлённым", "Be aware	[ˈbiː əˈwɛər ɒv]",
  "Завидовать", "Envy	[ˈɛnvɪ]",
  "Предавать", "Betray	[bɪˈtreɪ]",
  "Полагать", "Suppose	[səˈpəʊz]",
  "Интересоваться", "Wonder	[ˈwʌndə]",
  "Продумывать", "Think over [ˈθɪŋkˈəʊvə]",
  "Вести", "Lead	[liːd]",
  "Продвигать", "Promote	[prəˈməʊt]",
  "Участвовать", "Participate	[pɑːˈtɪsɪpeɪt]",
  "Опрашивать", "Interview	[ˈɪntəvjuː]",
  "Доверять", "Trust	[trʌst]"
]

const home = [
  "Мебель", "Furniture	['fɜːnɪʧə]",
  "Диван", "Sofa	['səufə]",
  "Стул", "Chair	['ʧeə]",
  "Табурет", "Stool	[stuːl]",
  "Стол", "Table	[ ˈteɪbl ]",
  "Письменный стол", "Desk	[ desk ]",
  "Журнальный столик", "Coffee table	['kɔfɪ  'teɪbl]",
  "Телевизор", "Tv set	[ˌtiː'viː set]",
  "Кресло", "Armchair	[ˌɑːm'ʧeə]",
  "Шкаф", "Wardrobe 	['wɔːdrəub]",
  "Книжный шкаф", "Bookcase 	['bukkeɪs]",
  "Шкаф для посуды", "Cupboard 	['kʌbəd]",
  "Кровать", "Bed	[ bed ]",
  "Двуспальная кровать", "Double bed	['dʌbl bed]",
  "Тумбочка", "Bedside table 	['bedˌsaɪd 'teɪbl]",
  "Обои", "Wall-paper	[wɔːl 'peɪpə]",
  "Настенный светильник", "Wall lamp 	[wɔːl læmp]",
  "Торшер", "Standard lamp	['stændəd læmp]",
  "Комод", "Chest of drawers 	[ʧest əv drɔːrz]",
  "Вешалка", "Coat rack	[kəut ræk]",
  "Двухъярусная кровать", "Bunk bed	[ˌbʌŋk bɛd]",
  "Туалетный столик", "Dressing-table	['dresɪŋ 'teɪbl]",
  "Стенка", "Wall unit	[wɔːl 'juːnɪt]",
  "Обивка", "Upholstery	[ʌp'həulst(ə)rɪ]",
  "Мягкая мебель", "Upholstered furniture 	[ ʌpˈhoʊlstəd ˈfɜːnɪtʃə(r) ]",
  "Домашняя утварь", "Household Stuff	['haushəuld stʌf]",
  "Раковина (на кухне)", "Sink	[sɪŋk]",
  "Ковёр", "	Carpet	['kɑːpɪt]",
  "Духовка", "Oven 	['ʌv(ə)n]",
  "Кран", "Tap	[tæp]",
  "Плита", "Cooker	['kukə]",
  "Пылесос", "Vacuum cleaner	 ['vækjuːm 'kliːnə]",
  "Стиральная машина", "Washing machine 	['wɔʃɪŋ mə'ʃiːn]",
  "Холодильник", "Fridge	[frɪʤ]",
  "Покрывало", "Cover	['kʌvə]",
  "Занавеска", "Curtain	['kɜːt(ə)n]",
  "Столовый сервиз", "Dinner set	['dɪnə set]",
  "Чайный сервиз", "Tea set 	[tiː set]",
  "Линолеум", "Linoleum	[lɪ'nəulɪəm]",
  "Коврик, циновка", "Mat	[mæt]",
  "Подушка", "Pillow	['pɪləu]",
  "Простыня", "Sheet	[ʃiːt]",
  "Штора", "Blind	[blaɪnd]",
  "Люстра", "Chandelier / lustre 	[ˌʃændə'lɪə] / ['lʌstə]",
  "Камин", "Fireplace	['faɪəpleɪs]",
  "Стерео-система", "Stereo system	['sterɪəu 'sɪstəm]",
  "Покрывало", "Bedspread	['bedspred]",
  "Ножевые изделия, металлические столовые приборы", "Cutlery	['kʌtl(ə)rɪ]",
  "Диванная подушка", "Cushion 	['kuʃ(ə)n]",
  "Сушилка для посуды", "Dish-drainer	['dɪʃ 'dreɪnə]",
  "Моющиеся обои", "Washing wall-paper 	['wɔʃɪŋ wɔːl 'peɪpə]",
  "Комнатное растение", "Houseplant	[hausplɑːnt]",
  "Оклеенный обоями", "Papered	['peɪpəd]",
  "Дверная ручка", "Door-handle	[dɔː ‘hændl]",
  "Наволочка", "Pillow-case	['pɪləu keɪs]",
  "Батарея центрального отопления", "	Radiator	['reɪdɪeɪtə]",
  "Швейная машина", "Sewing-machine	[səuɪŋmə'ʃiːn]",
  "Дверной глазок", "Spyhole	['spaɪhəul]",
  "Фарфоровая и фаянсовая посуда", "Crockery	['krɔk(ə)rɪ]",
  "Фарфор", "China	['ʧaɪnə]",
  "Приспособление, устройство, прибор", "Appliance	[ə'plaɪən(t)s]",
  "Овощерезка", "Vegetable cutter 	['veʤ(ə)təbl 'kʌtə]",
  "Вафельница", "Waffle-maker 	['wɔfl 'meɪkə]",
  "Центральное отопление", "Central heating	['sentr(ə)l 'hiːtɪŋ]",
  "Современные удобства", "Modern conveniences	['mɔd(ə)n kən'viːnɪən(t)siz]",
  "Мусоропровод", "Refuse-chute 	[rɪ'fjuːz ʃuːt]",
  "Вытяжка", "Cooker hood	['kukə hud]",
  "Части зданий", "Parts of Buildings	[pa:ts əv 'bɪldɪŋz]",
  "Лифт", "Lift	[lɪft]",
  "Потолок", "Ceiling 	['siːlɪŋ]",
  "Пол, этаж", "Floor	[ flɔː(r) ]",
  "Стена", "Wall	[ wɔːl ]",
  "Угол", "Corner	[ ˈkɔːnə(r) ]",
  "Крыша", "Roof	[ ruːf ]",
  "Вход", "Entrance	[ˈɛntr(ə)ns]",
  "Выход", "Exit	[ ˈeksɪt ]",
  "Коридор", "Corridor	['kɔrɪdɔː]",
  "Ванная комната 	Bathroom	['bɑːθruːm]",
  "Прихожая", "Hall	[hɔːl]",
  "Столовая", "Dining room	[daɪnɪŋ ruːm]",
  "Туалет", "Toilet 	['tɔɪlət]",
  "Балкон", "Balcony	['bælkənɪ]",
  "Гостиная", "Living room / lounge / sitting room / drawing room	[ˈlɪvɪŋ ruːm], [launʤ] / ['sɪtɪŋ ruːm] / ['drɔːɪŋ ruːm]",
  "Спальня", "Bedroom	['bedruːm]",
  "Кухня", "Kitchen	['kɪʧɪn]",
  "Гостевая комната", "Guest room	[gest ru:m]",
  "Крыльцо, подход", "Porch	[pɔːʧ]",
  "Лестничный пролёт", "Flight of stairs	[flaɪt əv steəz]",
  "Забор", "Fence	[fɛns]",
  "Изгородь", "Hedge	[heʤ]",
  "Кладовая ", "Storeroom	['stɔːrum]",
  "Подвал, фундамент", "Basement	['beɪsmənt]",
  "Двор", "Yard 	[jɑːd]",
  "Порог", "Threshold	['θreʃ(h)əuld]",
  "Подоконник", "Window-sill 	['wɪndəu-sɪl]",
  "Типы зданий", "Types of Buildings	[taɪps əv 'bɪldɪŋz]",
  "Гараж", "	Garage	['gærɑːʒ]",
  "Коттедж, домик", "Cottage	['kɔtɪʤ]",
  "Дворец", "Palace	['pælɪs] ",
  "Особняк, большой дом", "Mansion	['mæn(t)ʃ(ə)n]",
  "Студенческое общежитие", "Dormitory	['dɔːmɪt(ə)rɪ]",
  "Многоквартирный дом", "	Block of flats	[blɔk əv flæts]",
  "Одно/двух/... – комнатная квартира", "One/two/...-room flat	[. -ruːm flæt]",
  "Квартира", "Apartment	[ə'pɑːtmənt]",
  "Загородный дом", "Country-house	[ˌkʌntrɪ 'haus]",
  "Одно/двух/...этажныйдом", "One/two/...-storeyed house	[...-'stɔːrɪd haus]",
  "Недвижимое имущество", "eal estate	[ʹrıəl ı͵steıt]",
  "Один из двух домов под общей крышей", "Semi-detached house 	[ˌsemɪ dɪ'tæʧt haus]",
  "Небоскрёб", "Sky-scraper	[skaɪ 'skreɪpə]",
  "Въезжать, переезжать", "Move in/to	[ muːv ɪn/ tə]",
  "Передвигать мебель", "Move the furniture around	[muːv ðə 'fɜːnɪʧə ə'raund]",
  "Выходить на ... (об окнах)", "Look out onto	[luk aut 'ɔntuː]",
  "Передвигать", "Shift	[ʃɪft]",
  "Подновлять, ремонтировать, реконструировать", "Renovate	['renəveɪt]",
  "Ремонт", "Repair	[rɪ'peə]",
  "Снимать квартиру", "Rent a flat	[rent ə flæt]",
  "Проживать в одной комнате с кем-либо", "Share a room with smb	[ʃeə ə ru:m wɪð<smb>]",
  "Починить, исправить", "Put things right / fix	[put θɪŋz raɪt] / [fiks]",
  "Просторный", "Spacious	['speɪʃəs]",
  "Побелка; белить, делать побелку", "Whitewash 	['waɪtwɔʃ]",
  "Новоселье", "Housewarming party['hausˌwɔːmɪŋ 'pɑːtɪ]"
  ]

const city = [
"Места", "Places	[ˈpleɪsɪz]",
"Скорая помощь", "Ambulance 	[ˈæmbjələns ]",
"Продуктовый магазин", "Grocery store	[ˈɡrəʊsəri stɔː ]",
"Билетная касса", "Ticket office	[ˈtɪkɪt ˈɒfɪs ]",
"Концертный зал", "Concert hall	[kənˈsɜːt hɔːl ]",
"Торговый центр", "Shopping mall	[ˈʃɒpɪŋ mɔːl ]",
"Международный аэропорт", "International airport	[ˌɪntəˈnæʃn̩əl ˈeəpɔːt ]",
"Стадион", "Stadium	[ˈsteɪdɪəm ]",
"Вокзал", "Railway station	[ˈreɪlweɪ ˈsteɪʃn̩ ]",
"Собор", "Cathedral	[kəˈθiːdrəl]",
"Зоопарк", "Zoo	[zuː ]",
"Банк", "Bank	[bæŋk ]",
"Рынок", "Market	[ˈmɑːkɪt ]",
"Полицейский участок", "Police station	[ pəˈliːs ˈsteɪʃn̩ ]",
"Дом", "House	[ haʊs ]",
"Школа", "	School	[ skuːl ]",
"Университет", "University	[ ˌjuːnɪˈvɜːsəti ]",
"Церковь", "Church	[ tʃɜːtʃ ]",
"Больница", "Hospital	[ ˈhɒspɪtl ]",
"Музей", "Museum	[ mjuˈziːəm ]",
"Театр", "Theater	[ ˈθɪə.tər ]",
"Обменник", "Currency exchange	[ˈkʌrənsi ɪkˈstʃeɪndʒ ]",
"Банкомат", "ATM	[ˌeɪtiːˈem ]",
"Кино", "	Cinema	[ ˈsɪnəmə ]",
"Памятник", "Monument	[ˈmɒnjʊmənt]",
"Мост", "Bridge	[brɪdʒ ]",
"Консульство", "Consulate	[ˈkɒnsjʊlət ]",
"Пожарная часть", "Fire station	[ˈfaɪə ˈsteɪʃn̩ ]",
"Заправка", "Gas station	[ɡæs ˈsteɪʃn̩ ]",
"Район", "District	[ˈdɪstrɪkt ]",
"Центр города", "Downtown = the city centre	[ ˈdaʊntaʊn = ðə ˈsɪti ˈsentə ]",
"Окраина города", "The outskirts	[ ði ˈaʊtskɜːts ]",
"Загород", "Countryside	[ˈkʌntrisaɪd ]",
"Парк аттракционов", "Amusement park	[əˈmjuːzmənt pɑːk ]",
"Каток", "Skating rink	[ˈskeɪtɪŋ rɪŋk ]",
"Казино", "Casino	[kəˈsiːnəʊ ]",
"Тюрьма", "Prison = jail	[ˈprɪzn̩ ] = [ʤeɪl]",
"Замок", "Castle	[ˈkɑːsl̩]",
"Крепост", "Fortress	[ˈfɔːtrɪs]",
"Здание городского управления", "City hall	[ˈsɪti hɔːl]",
"Разводной мост", "Drawbridge	[ˈdrɔːbrɪdʒ ]",
"Башня", "Tower	[ˈtaʊə ]",
"Храм", "emple	[ˈtempl̩ ]",
"Часовня", "Chapel	[ˈtʃæpl̩ ]",
"Мечеть", "Mosque	[mɒsk ]",
"Монастырь", "Monastery	[ˈmɒnəstri ]",
"Здание суда", "Courthouse	[ˈkɔːthaʊs ]",
"Небоскреб", "Skyscraper	[ˈskaɪskreɪpə ]",
"Галерея искусств", "Art gallery	[ɑːt ˈɡæləri ]",
"Выставка", "Exhibition	[ˌeksɪˈbɪʃn̩ ]",
"Консерватория", "Conservatory	[kənˈsɜːvətr̩i ]",
"Опера", "Opera house	[ˈɒprə ˈhaʊs ]",
"Концерт", "Concert = gig	['kɔnsət] = [ɡɪɡ ]",
"Концертная площадка", "Music venue	[ˈmjuːzɪk ˈvenjuː ]",
"Театральное представление", "Theatrical performance	[θiˈætrɪk(ə)l̩ pə'fɔːmən(t)s]",
"Игровой автомат", "Slot-machine	[ˈslɒt məʃiːn ]",
"Универмаг", "Department store	[dɪˈpɑːtmənt stɔː ]",
"Газетный киоск", "Newsstand	[ˈnjuːzstænd ]",
"Посольство", "Embassy 	[ˈembəsi ]",
"Юридическая фирма", "Law office	[lɔː ˈɒfɪs ]",
"Роддом", "Maternity home	[məˈtɜːnɪti həʊm ]",
"Кладбище", "Cemetery	[ˈsemətri ]",
"Регистратура, ЗАГС", "Registry office	[ˈredʒɪstri ˈɒfɪs ]",
"Аэропорт внутренних авиалиний", "Domestic airport	[dəˈmestɪk ˈeəpɔːt ]",
"Страховая компания", "Insurance company	[ ɪnˈʃʊərəns ˈkʌmpəni ]",
"Прачечная", "Laundry	[ˈlɔːndri ]",
"Ремонт обуви", "Shoe repair	[ʃuː rɪˈpeə ]",
"Зона отдыха", "Recreation area	[ˌrekrɪˈeɪʃn̩ ˈeəriə ]",
"Заповедник", "Sanctuary	[ˈsæŋktʃʊəri ]",
"Культурный центр", "Culture centre	[ˈkʌltʃə ˈsentə ]",
"Очень крупный город", "Metropolis	[məˈtrɒpəlɪs ]",
"Деловой район", "Business area	[ˈbɪznəs ˈeəriə ]",
"Жилой район", "Residential area	[ˌrezɪˈdenʃl̩ ˈeəriə ]",
"Правительственный район", "Government area	[ˈɡʌvənmənt ˈeəriə ]",
"Район, окрестность", "Neighbourhood = vicinity	[ ˈneɪbəhʊd = vɪˈsɪnɪti ]",
"Пригород", "Suburb	[ ˈsʌbɜːb ]",
"Загород", "Countryside	[ˈkʌntrisaɪd ]",
"Безопасный", "Safe	[seɪf ]",
"Переполненный, многолюдный", "Crowded	[ ˈkraʊdɪd ]",
"Передвижение по городу", "Getting around	[ˈɡetɪŋ əˈraʊnd ]",
"Площадь", "Square	[skweə ]",
"Главная дорога", "Main road	[meɪn rəʊd ]",
"Светофор", "Traffic lights	[ˈtræfɪk laɪts ]",
"Пешеход", "Pedestrian	[pɪˈdestrɪən ]",
"Канал", "Canal	[kəˈnæl ]",
"Набережная", "Embankment	[en'bankment ]",
"Тротуар", "Pavement = sidewalk	[ˈpeɪvmənt = ˈsaɪdwɔːk ]",
"Пешеходный переход", "Crossing = zebra	[ˈkrɒsɪŋ = ˈzebrə ]",
"Подземный переход", "Underground crossing	[ˈʌndəɡraʊnd ˈkrɒsɪŋ ]",
"Перекресток", "Intersection = crossroads	[ˌɪntəˈsekʃn̩ = ˈkrɒsrəʊdz ]",
"Общественный транспорт", "Public transport	[ˈpʌblɪk ˈtrænspɔːt ]",
"Стоянка такси", "Taxi rank	[ˈtæksi ræŋk]",
"Второстепенная дорога", "Side street	[saɪd striːt ]",
"Проездной билет", "City pass	[ˈsɪtipɑːs ]",
"Автобусный маршрут", "Bus route	[bʌs ruːt ]",
"Велосипедная дорожка", "Cycle lane	[ˈsaɪkl̩ leɪn ]",
"Фуникулер", "Cable car	[ˈkeɪbl̩ kɑː ]",
"Гавань, порт", "Harbour	[ˈhɑːbə ]",
"Док, пристань", "Dock	[ˈdɒk ]",
"Двухэтажный автобус", "Double-decker bus	[ˌdʌbl̩ ˈdekə bʌs ]",
"Второстепенная дорога", "Side street	[saɪd striːt ]",
"Квартал", "Block	[ˈblɒk ]",
"Урна", "Litter bin	[ ˈlɪtə bɪn ]",
"Мусорный бак	", "Trash container	[træʃ kənˈteɪnə ]",
"Стройка", "Building site	[ˈbɪldɪŋ saɪt ]",
"Люк", "Manhole	[ˈmænhəʊl ]",
"Уличный фонарь", "Streetlight	[street light]",
"Потеряться", "To get lost	[ˈɡet lɒst ]",
"Тур по городу", "City tour	[ˈsɪti tʊə ]",
"Экскурсия", "Excursion 	[ɪkˈskɜːʃn̩ ]",
"Гид", "A guide 	[ə ɡaɪd ]",
"Достопримечательности", "Sights 	[saɪts ]",
"Туристы", "Visitors = tourists 	[ˈvɪzɪtəz = ˈtʊərɪsts ]",
"Входная плата", "Admission fee / admission charge	[ədˈmɪʃn̩ fiː ] / [ədˈmɪʃn̩ tʃɑːdʒ ]",
"Цена", "Fare = price 	[feə = praɪs ]",
"Путеводитель", "Guidebook 	[ ˈɡaɪdbʊk ]",
"Историческая достопримечательность", "Historic landmark 	[hɪˈstɒrɪk ˈlændmɑːk ]",
"План поездки", "Travel itinerary 	[ˈtrævl̩ aɪˈtɪnərəri ]",
"Осматривать достопримечательности", "To go sightseeing	[ɡəʊ ˈsaɪtsiːɪŋ ]",
"Поехать на экскурсию", "To take a tour 	[teɪk ə tʊə ]",
"В городе за рулём", "Driving in the city	[ˈdraɪvɪŋ ɪn ðə ˈsɪti ]",
"Аренда машины", "Car hire = car rental	[kɑː ˈhaɪə = kɑː ˈrentl̩ ]",
"Мойка", "Car wash 	[kɑː wɒʃ ]",
"Авторемонт", "Car repair	[kɑː rɪˈpeə ]",
"Пробка", "Traffic jam 	[ˈtræfɪk dʒæm] ",
"Шиномонтаж", "Tyre fitting	[ˈtaɪə ˈfɪtɪŋ ]",
"Дорога с односторонним движением", "One-way street	[ˌwʌnˈweɪ striːt ]",
"Дорожный знак", "Road sign	[rəʊd saɪn ]",
"Тупик", "Dead end	[ded end ]",
"Парковка", "Car park = parking lot 	[kɑː pɑːk = ˈpɑːkɪŋ lɒt ]",
"Счетчик платы за стоянку", "Parking meter	[ˈpɑːkɪŋ ˈmiːtə ]",
"Многоуровневая парковка", "Multi-storey car park	[ˈmʌlti -ˈstɔːri kɑː pɑːk ]",
"Перекрёсток с круговым движением", "Roundabout	[ˈraʊndəˌbaʊt ]",
"Дорожные работы", "Road works	[rəʊd ˈwɜːks ]",
"Инспектор дорожного движения", "Traffic warden	[ˈtræfɪk ˈwɔːdn̩ ]",
"Эвакуировать машину", "To tow away a car	[təʊ əˈweɪ ə kɑː ]",
"Заплатить штраф", "Pay a fine	[peɪ ə faɪn ]"
]

const shopping  = [
"Магазины", "Shops	[ʃɔps]",
"Книжный", "Bookstore	[bʊkstɔ:]",
"Косметика", "Cosmetics shop	[kɒz'mɛtɪks ʃɒp]",
"Аптека", "Drugstore / chemist's / pharmacy	[drʌgstɔ:] / ['kemɪsts] / ['fɑːməsɪ]",
"Булочная", "Bakery	[beɪkəri]",
"Кондитерская", "Candy shop	['kændɪ ʃɔp]",
"Оптика", "Optometrist	[ɒpʹtɒmıtrıst]",
"Бутик", "Boutique	[bu:'ti:k]",
"Рынок", "Market	['ma:kɪt]",
"Мясной м-н", "Butcher's	[bʊtʃəz]",
"М-н обуви", "Footwear / shoe shop 	[fʊtweə] / [ʃuː ʃɔp] ",
"Торговый центр", "Mall	[mɔ:l]",
"Ювелирный м-н", "Jewellery store	[dʒu:əlri stɔ:]",
"Электроника", "Electronics	[ɪlɛk'trɒnɪks]",
"Мебель", "Furniture store	[fɜ:nɪtʃə stɔ:]",
"Спортивные товары", "Sport goods / sports store	[spɔ:t gʊdz] / [spɔ:ts stɔ:]",
"Канцелярия", "Stationer's	[steɪʃnəz]",
"М-н игрушек", "Toy store	[tɔɪ stɔ:]",
"Антикварный", "Antique shop	[æn'ti:k ʃɒp]",
"Газетныйкиоск", "Newsagent's / news-stand	[nju:z 'eɪdʒənts] / [ʹnju:zstænd]",
"Дисконт центр", "Discount store	[dɪskaʊnt stɔ:]",
"М-н тканей", "Fabric store	[fæbrɪk stɔ:]",
"Магазин посуды", "Crockery / cookware	['krɔk(ə)rɪ] / ['kukweə]",
"Цветочный магазин", "Florist 	['flɔrɪst]",
"Сеть стоковых магазинов", "Outlet mall	['autlet mɔːl]",
"Ломбард", "Pawnshop 	['pɔːnʃɔp]",
"Винный магазин", "Liquor store	['lɪkə stɔː]",
"Блошиный рынок", "Flea market	[fli: 'ma:kɪt]",
"Галантерея", "Haberdashery	[hæbədæʃəri]",
"Зоо магазин", "Pet shop	[pɛt ʃɒp]",
"Бытовые приборы", "Appliance store	[ə'plaɪəns stɔ:]",
"Сетевой м-н", "Chain store	[tʃeɪn stɔ:]",
"Платить наличными", "To pay (in) cash	[peɪ (in) kæʃ]",
"Платить кредиткой", "To pay by a credit card	[peɪ baɪ ə 'krɛdɪt ka:d]",
"Покупать", "To purchase	[pɜ:tʃəs]",
"Количество и упаковка", "Quantities and package	['kwɔntətɪz& 'pækɪʤ]",
"Банка (сливок)", "Jar of (cream)	[ʤɑːr əv]",
"Пачка / пакет (молока, сигарет)", "Carton / packet of (milk, cigarettes)	['kɑːt(ə)n / 'pækɪt əv]",
"Кусок (хлеба)", "Slice / piece of (bread)	[slaɪs / pi:s əv]",
"Дюжина (яиц)", "Dozen of (eggs)	['dʌz(ə)n əv]",
"Бутылка (молока)", "Bottle of (milk)	['bɔtl əv]",
"Коробка (печенья)", "Box of (cookies)	[bɔks əv]",
"Консервная банка (персиков)", "Can / tin of (peaches)	[kæn / tɪn əv]",
"Плитка (шоколада)", "Bar of (chocolate)	[ba:r əv]",
"Кусок (мыла)", "Bar of (soap)	[ba:r əv]",
"Кусок (говядины)", "Cut of (beef)	[kʌt əv]",
"Гроздь(винограда)", "Bunch of (grapes)	[bʌnʧ əv]",
"Связка(ключей)	", "Bunch of (keys)	[bʌnʧ əv]",
"Полдюжины", "Half a dozen	[ha:f ə 'dʌz(ə)n]",
"Клубок (шерсти)", "Ball of (wool)	[bɔːl əv]",
"Катушка (ниток)", "Reel of (thread)	[ri:l əv]",
"Рулон (бумаги)", "Roll of (paper)	[rəul əv]",
"Мелочь, сдача", "Change	[ʧeɪnʤ]",
"Быть в продаже	", "o be in  stock	[bi: ɪn stɔk]",
"Не иметься в продаже", "To be out of stock	[bi: ʹaʋt əv stɔk]",
"Уценка", "Mark-down	['mɑːk daun]"

]

const travelling = [
"Путешествие","Travelling	[ 'trævliŋ ]",
"Отпуск","Vacation, leave	[və'keɪʃn], [liːv]",
"Каникулы","(school/university) vacation	[(skuːl / juːnɪ'vɜːsətɪ) və'keɪʃn]",
"Иностранный","Foreign	['fɔrɪn]",
"Путешествие по туристической путевке","Package tour	[ 'pækiʤ tuə ]",
"Морской круиз","Cruise	[ kru:z ]",
"Тур","Tour	[tuə]",
"Туризм","Tourism	['tuərɪzm]",
"Путешествие, длительная поездка","Journey	[ ʤə:ni ]",
"Путешествие, короткая поездка","Trip, short journey	[ trip ], [ʃɔːt ʤə:ni ]",
"Бюро путешествий","Travel agency, tourist agency	[ trævl 'eiʤənsi],['tuərist 'eiʤənsi ]",
"Пешеходный поход, экскурсия","Hike	[ haik ]",
"Путешествовать","To travel	[ ˈtravəl]",
"Ехать/поехать заграницу","To go abroad	[  gəu ə'brɔːd]",
"Совершить путешествие","To make a journey	[ meik ə ʤə:ni ]",
"Путешествовать, пользуясь попутным транспортом","To hitch-hike	[ hiʧ-haik ]",
"Любить путешествовать","To be fond of travelling	[ bi: fɔnd əv 'trævliŋ ]",
"Отдыхать","To be on vacation; to rest, 	[ bi: ɔn və'keɪʃn], [ rest]",
"Купить туристическую путевку","To buy a package tour	[  bai ə 'pækiʤ tuə ]",
"Отправиться в путешествие","To go on for a journey	[ gəu ɔn fɔ:r ə ʤə:ni ]",
"Совершить путешествие","To make a journey	[ meik ə ʤə:ni ]",
"Отправиться в двухдневный поход","To go on a two-day tour	[ gəu ɔn ə tu:-dei tuə ]",
"Билеты","Tickets	['tɪkɪts]",
"Билет на поезд, самолет","A ticket for a train/ plane	[ə 'tikit fɔ:r ə trein /plein]",
"Билетная касса","Booking office	[ 'bʋkɪŋ 'ɔfis ]",
"Забронировать билеты","To book tickets	[ buk 'tikits ]",
"Билет в один конец","One-way ticket	[ˌwʌn 'weɪ 'tikit ]",
"Билет (туда и обратно)","Return ticket	[rɪ'tɜːn 'tikit ]",
"Достать билеты	","o get tickets	[ get 'tikits ]",
"Купить билеты заранее","To book tickets in advance	[buk 'tikits in əd'vɑːn(t)s]",
"Предъявить билеты","To produce tickets	[ prə'dju:s 'tikits ]",
"Пассажир без билета","Stowaway	['stəuəˌweɪ]",
"Транспорт","Transport	[træn'spɔːt]",
"Аэропорт","Airport	['eəpɔːt]",
"Корабль","Ship	[ʃɪp]",
"Такси","Taxi	['tæksɪ]",
"Самолёт","(air)plane	['eəpleɪn]",
"Поезд","Train	[treɪn]",
"Машина","Car, automobile	[kɑː] ['ɔːtəməubiːl]",
"Багаж","Luggage, baggage	[ 'lʌgiʤ], ['bægiʤ ]",
"Паспорт","Passport	['pɑːspɔːt]",
"Автобусная остановка","Bus stop	[bʌs stɔp]",
"Посадка","Boarding	[ 'bɔ:rdɪŋ ]",
"Таможня","Customs	['kʌstəms]",
"Отправление","Departure	[ di'pɑ:ʧə ]",
"Вокзал","(railroad/train) station	['reɪlrəud/treɪn 'steɪʃn]",
"Прибытие","Arrival	[ ə'raivl ]",
"Багаж","Luggage, baggage	[ 'lʌgiʤ], ['bægiʤ ]",
"Ручной багаж","Hand luggage	[ hænd 'lʌgiʤ ]",
"Садиться/сесть (на что-то)	","To get on, 	[ get ɔn]",
"Багажный транспортер","Baggage carousel	['bægɪʤ ˌkærə'sel]",
"Зона получения багажа","Baggage claim area	['bægɪʤ kleɪm 'eərɪə]",
"Контрольно-пропускной пункт","Security checkpoint	[sɪ'kjuərətɪ 'ʧekpɔɪnt]",
"Металлоискатель","Metal detector	[ˈmetl dɪ'tektə]",
"Виза","Visa	['viːzə]",
"Камера хранения","Cloak-room	['kləukrum]",
"Вертолёт","Helicopter	['helɪkɔptə]",
"Электричка","Suburban train	[sə'bæːbən treɪn]",
"Порт, гавань","Port / harbour	[pɔːt] / ['hɑːbə]",
"Яхта","Yacht	[jo:t]",
"Круизный лайнер","Cruise liner	[kruːz 'laɪnə]",
"Паром","Ferry	['ferɪ]",
"Тележка","Luggage carrier	[ 'lʌgiʤ 'kærɪə]",
"Рюкзак","Backpack	['bækpæk]",
"Чемодан","Suit case	[ sju:t keis ]",
"Большой чемодан, сундук","Trunk	[ trʌŋk ]",
"Тележка","Luggage carrier	[ 'lʌgiʤ 'kærɪə]",
"Бензин","Benzine, petrol, gas	['benziːn]/['petrəl]/[gæs]",
"Стоянка такси","Cab rank	[kæb ræŋk]",
"Садиться/сесть (начто)","To get on, 	[ get ɔn]",
"Высаживаться","To get off, alight from	[ get ɔf], [ə'laɪt frɔm]",
"Отправляться/отправиться","To set out, to leave, to depart	[ set aut], [liːv], [dɪ'pɑːt]",
"Прибывать/прибыть","To arrive	[ ə'raiv]",
"Взлетать","To leave the ground	[liːv ðə graund]",
"Приземляться/приземлиться","To land, to touch down	[ lænd], [tʌʧ daun]",
"Взлетно-посадочная полоса","Runway	['rʌnweɪ]",
"Отправляться по расписанию","To leave on time	[ li:v ɔn taim ]",
"Идти по расписанию (о поезде, самолете)","To keep to schedule	[ ki:p tə 'skedju:l ]",
"Опаздывать (о поезде и т.д.)","To be behind schedule	[bi: bi'haind 'skedju:l]",
"Сдать вещи в багаж","To check one's luggage	[ʧek <one's> 'lʌgiʤ ]",
"Багажная квитанция","Luggage receipt	[ 'lʌgiʤ ri:'si:t ]",
"Бюро находок","Lost property office	[ lɔst 'prɔpəti 'ɔfis ]",
"Путешествовать налегке","To travel light	[ trævl lait ]",
"Таможенная декларация","Customs declaration form	['kʌstəms ˌdeklə'reɪʃn fɔːm]",
"Размещение, поселение","Accommodation	[əˌkɔmə'deɪʃ(ə)n]",
"Гостиница, отель","Hotel	[həu'tel]",
"Счет","Bill	[bɪl]",
"Питание по программе «все включено»","All inclusive	[ɔːl ɪn'kluːsɪv]",
"Курорт","Resort	[ ri'zɔ:t ]",
"Час, до которого необходимо освободить номер в день отъезда","Check-out time	[ʧek aut taɪm]",
"Мотель","Motel	[məu'tel]",
"Хостел","Hostel	['hɔst(ə)l]",
"Скидка","Discount	['dɪskaunt]",
"Питание: завтрак","B&b — bed and breakfast	[ˌbiːən(d)'biː]",
"Полупансион (как правило, завтрак и ужин)","Hb — half board	[ˌhɑːf'bɔːd]",
"Кемпинг","Camp site	[kæmpsaɪt]",
"Гостиница для семейных","Family hotel	['fæməlɪ (h)ə(u)'tel] ",
"Пятизвёздочный отель","Luxury hotel	['lʌkʃərɪ (h)ə(u)'tel]",
"Заранее","In advance	[ɪn əd'vɑːn(t)s]",
"Стандартный номер","Standard room	['stændəd ruːm]",
"Номер «люкс»","Suite room	[swiːt ruːm]",
"Двухместный номер с двумя кроватями","Twin room	[twɪn ruːm]",
"Двухместный номер с одной двуспальной кроватью","Double room	['dʌbl ruːm]",
"Стойка администратора","Reception desk	[rɪ'sepʃ(ə)n desk]",
"Забронировать гостиничный номер","To make a reservation for a room	[meɪk ə ˌrezə'veɪʃn fɔːr ə ruːm]",
"Бронировать","To book 	[buk]",
"Подтверждение бронирования","Booking confirmation	['bukɪŋ ˌkɔnfə'meɪʃ(ə)n]",
"Заполнить форму","To fill in a form	[fɪl ɪn ə fɔːm]",
"Вселиться в гостиницу (зарегистрироваться)	","To check in	[ʧek ɪn]",
"Выехать из гостиницы","To check out	[ʧek aut]",
"Оплатить услуги","To pay for services	[peɪ fɔː 'sɜːvɪsɪz]",
"В стоимость включено","Rate includes	[reɪt ɪn'kluːdz]",
"Оплата в местной валюте","Payment in local currency	['peɪmənt ɪn 'ləuk(ə)l 'kʌrənsɪ]",
"Расплатиться наличными","To pay cash	[peɪ kæʃ]",
"Платить по картe","To pay with a card	[peɪ wɪð ə kɑːd]",
"Взимать плату за нанесенный ущерб","To take a damage charge	[teɪk ə 'dæmɪʤ ʧɑːʤ]",
"Взимать плату за пользование платными услугами","To take an extra room charge	[teɪk ən 'ekstrə ruːm ʧɑːʤ]",
"Налог на добавленную стоимость","Value added tax	['væljuː æ̱dɪd tæks]",
"Минимальный срок пребывания","A minimum length of stay	['mɪnɪməm le̱ŋθ əv steɪ]",
"У вас есть свободные номера?","Have you got any accomodations?	[hæv juː got 'enɪ ə‚kɒmə’deɪʃənz]",
"Сколько стоит номер в сутки?","What do you charge for a room per day?	[wɔt du: ju: ʧɑːʤ fɔːr ə ruːm pɜː deɪ]",
"Входит ли в стоимость номера питание?","Does the charge for the room include meals?	[dʌz ðə ʧɑːʤ fɔː ðə ruːm ɪn'kluːd miːlz]",
"У вас есть что-нибудь подешевле?","Do you have anything cheaper?	[du: ju: hæv 'enɪθɪŋ ʧiːpə]",
"Мы бы хотели заселиться/выехать.","We would like to check in/check out.	[wiː wud laɪk tə ʧek ɪn/ tə ʧek aut]",
"Мне нужна комната на одного.","I need a single room.	[ai niːd ə 'sɪŋgl ruːm]",
"Мне нужна комната на двоих.","I need a double room.	[ai niːd ə 'dʌbl ruːm]",
"В данный момент свободных номеров нет.","At the moment there are no rooms available.	[æt ðə 'məumənt ðeər ɑː nəu ruːmz ə'veɪləbl]",
"У меня забронирован номер.","I have a reservation.	[ai hæv ə ,rezə'veiʃən]",
"Во сколько происходит выселение из отеля?","What time is checkout?	[wɔt taim iz 'tʃekaʋt]",
"Я уезжаю завтра днём.","I'm leaving tomorrow afternoon.	[aɪm liːvɪŋ tə'mɔrəu ˌɑːftə'nuːn]"

]

const health = [
"Здоровый образ жизни", "Healthy life-style	['helθɪ 'laɪf staɪl]",
"Здоровье", "Health 	[helθ]",
"Улучшать здоровье", "To improve one’s health 	[ɪm'pruːv<one’s>helθ]",
"Вредить здоровью", "To damage one’s health	['dæmɪʤ<one’s>helθ]",
"Быть полезным для здоровья", "To be good for one’s health	[bi: gud fə<one’s>helθ]",
"Быть вредным для здоровья", "To be bad for one’s health	[bi: bæd fə<one’s>helθ]",
"Поддерживать хорошую физическую форму", "To stay fit	[stei fɪt]",
"Упражняться", "To exercise	['eksəsaɪz]",
"Заниматься спортом", "To play sports	[plei spɔːts]",
"Здоровая пища", "Healthy food	['helθɪ fuːd]",
"Соблюдатьдиету", "To be on a diet	[biː ɔn ə 'daɪət]",
"Сесть надиету", "To go on a diet	[gəu ɔn ə 'daɪət]",
"Сбалансированная диета", "Balanced diet	['bælən(t)st  'daɪət]",
"Болезнь", "Illness	 [ˈɪlnəs]",
"Болеть (бытьбольным)", "To be ill (br.) / to be sick (am.)	[biː ɪl] / [biː sɪk]",
"Заболевать", "To fall / get  ill / sick	[fɔːl] / [get ɪl / sɪk]",
"Заболеть чем-то", "To become sick with ……	[bɪ'kʌm sɪk wɪð]",
"Чувствовать себя лучше", "To feel better	[fiːl 'betə]",
"Чувствовать себя хуже", "To feel worse	[fiːl wɜ:s]",
"Идти на поправку", "To get better	[get 'betə]",
"Выздоравливать", "To recover	[rɪ'kʌvə]",
"Грипп", "Flu 	[fluː]",
"Заразиться гриппом", "To catch the flu 	[kæʧ ðə fluː]",
"Простуда", "Cold	[kəuld]",
"Простудиться", "To catch a cold 	[kæʧ ə kəuld]",
"Болеть простудой", "To have a cold	[həv ə kəuld]",
"Запор", "Constipation	[ˌkɔnstɪ'peɪʃ(ə)n]",
"Диарея", "Diarrhea	[ˌdaɪə'rɪə]",
"Отравление", "Poisoning	['pɔɪz(ə)nɪŋ]",
"Сердечный приступ", "Heart attack	['hɑ:t əˌtæk]",
"Тонзиллит", "Tonsillitis	[ˌtɔns(ə)'laɪtɪs]",
"Ангина", "Quinsy	['kwɪnzɪ]",
"Аппендицит", "Appendicitis	[əˌpendɪ'saɪtɪs]",
"Воспаление", "Inflammation	[ˌɪnflə'meɪʃ(ə)n]",
"Воспаление", "легких	Pneumonia	[nju:'məunɪə]",
"Гастрит", "Gastritis	[gæs'traɪtɪs]",
"Изжога", "Heartburn	['hɑ:tbɜ:n]",
"Туберкулез", "Tuberculosis	[t(j)u:ˌbɜ:kjə'ləusɪs]",
"Язва (внутренняя)", "Ulcer	['ʌlsə]",
"Язва (наружная)", "Sore	[sɔ:]",
"Повышенно давление", "High blood pressure	[haɪ blʌd 'preʃə]",
"Пониженное давление", "Low blood pressure	[ləu blʌd 'preʃə]",
"Близорукость", "Short-sightedness	[ˌʃɔ:t 'saɪtɪdnəs]",
"Дальнозоркость", "Far-sightedness	[fɑ: 'saɪtɪdnəs]",
"Аллергия", "	Allergy	['æləʤɪ]",
"Иметъ аллергию на …", "	To be allergic to …	[biː ə'leʤɪk tə]",
"Лекарство", "Medicine	['medɪsɪn]",
"Цветение", "Pollen	['pɔlən]",
"Запахи", "Odours	['əudəz]",
"Домашняя пыль", "Household dust	['haushəuld dʌst]",
"Симптомы", "	Symptoms	[ˈsɪmptəmz]",
"Головная боль", "Headache	['hedeɪk]",
"Боль в ухе", "Earache	['ɪəreɪk]",
"Боль в животе", "Stomach ache	['stʌməkeɪk]",
"Боль в спине", "Backache	['bækeɪk]",
"Зубная боль", "Toothache	['tuːθeɪk]",
"Кашель", "Cough	[kɔf]",
"Больное горло", "Sore throat	[sɔː  θrəut]",
"Боль в груди", "Pain in one’s chest	[peɪn ɪn<one’s>ʧest]",
"Насморк", "Running nose	['rʌnɪŋ nəuz]",
"Заложенный нос", "Stuffy nose	['stʌfɪ nəuz]",
"Озноб", "Chills	[ʧɪlz]",
"Тошнота", "Nausea	['nɔːsɪə]",
"Испытывать тошноту", "To feel sick	[fiːl 'sɪk]",
"Высокая температура", "High temperature	[haɪ 'temp(ə)rəʧə]",
"Иметь повышенную температуру", "To have a temperature	[həv ə 'temp(ə)rəʧə]",
"Жар", "Fever	['fiːvə]",
"Сыпь", "Rash	[ræʃ]",
"Плохо себя чувствовать", "To be not well 	[bi: nɔt wel]",
"Бессонница", "Insomnia	[ɪn'sɔmnɪə]",
"Страдать бессонницей", "To suffer from insomnia	['sʌfə frɔm ɪn'sɔmnɪə]",
"Боль", "Pain	[peɪn]",
"У меня болит горло.", "I have a sore throat.	[aɪ həv ə sɔː θrəut]",
"У меня болит голова.", "I have a headache.	[aɪ həv ə 'hedeɪk]",
"У меня болит печень.", "I have a pain in my liver.	[aɪ həv ə peɪn ɪn maɪ 'lɪvə]",
"У меня болит поясница.", "I have a pain in the small of the back.	[aɪ həv ə peɪn ɪn ðə smɔːl əv ðə bæk]",
"У меня болят глаза.", "I have sore eyes.	[aɪ həv sɔ:r aɪz]",
"Болеть (о части тела)", "To hurt	[hɜ:t]",
"У меня болит рука.", "My hand hurts.	[maɪ hænd hɜ:ts]",
"Больно!", "It hurts!	[ɪt hɜ:ts]",
"У меня болит зуб.", "I have a toothache.	[aɪ  həv ə 'tuːθeɪk]",
"У меня сломался зуб.", "I have a broken tooth.	[aɪhəv ə 'brəuk(ə)n tuːθ]",
"Пломба", "Filling	['fɪlɪŋ]",
"У меня выпала пломба.", "I have lost a filling.	[aɪ həv lɔst ə 'fɪlɪŋ]",
"Лечить зуб", "To treat a tooth	[triːt ə tuːθ]]",
"Травма", "Injury	['ɪnʤ(ə)rɪ]",
"Порез", "Cut	[kʌt]",
"Нарыв", "Abscess 	['æbsəs]",
"Опухание", "Swelling	['swelɪŋ]",
"Вывих", "Dislocation	[ˌdɪsləu'keɪʃ(ə)n]",
"Вывихнуть", "To dislocate	['dɪsləukeɪt]",
"Перелом", "Fracture	['frækʧə]",
"Растяжение", "Strain 	[streɪn]",
"Ожог", "Burn	[bɜːn]",
"Кровь", "Blood 	[blʌd]",
"Кровоточить", "To bleed 	[bli:d]",
"Кровотечение", "Bleeding	[bli:dɪŋ]",
"Лечение", "Treatment	['triːtmənt]",
"Лечить (применять лечение) от …", "To treat for …	[triːt fɔː]",
"Лечить, исцелять (быть средством лечения)", "To cure	[kjuə]",
"Лечить, заживлять", "To heal	[hiːl]",
"Традиционная медицина", "Traditional medicine	[trə'dɪʃ(ə)n(ə)l 'medɪsɪn]",
"Анализ", "Test 	[test]",
"Анализ крови", "Blood test 	[blʌd test] ",
"Делать анализ", "To do a test 	[du ə test]",
"Делать рентген	", "o do an X-ray	[du ən 'eksreɪ ]",
"Делать укол", "To give an injection	[gɪv ən ɪn'ʤekʃ(ə)n]",
"Измерять давление", "To take one's blood pressure	[teɪk<one's>blʌd 'preʃə]",
"Измерять температуру", "To take <one's> temperature	[teɪk<one's> 'temp(ə)rəʧə]",
"Измерять пульс", "To take a pulse	[teɪk ə pʌls]",
"Выписать рецепт", "To write out a prescription	[raɪt aut ə prɪs'krɪpʃ(ə)n]",
"Принимать лекарство", "To take some medicine	[teɪk sʌm 'medɪsɪn]",
"Соблюдать постельный режим", "To stay in bed	[steɪ ɪn bed]",
"Грелка", "Hot-water bottle	[hɔt 'wɔːtə 'bɔtl]",
"Полоскать", "To gargle	['gɑːgl]",
"Прогревать", "To warm	[wɔːm]",
"Бинтовать", "To bandage 	['bændɪʤ]",
"Операция", "Surgery	['sɜːʤ(ə)rɪ]",
"Перенести операцию", "To undergo/ have a surgery	[ˌʌndə'gəu / həv ə 'sɜːʤ(ə)rɪ]",
"Прививка", "Vaccination 	[ˌvæksɪ'neɪʃ(ə)n]",
"Делать прививку (кому-л.) От", "To vaccinate against ….	['væksɪneɪt ə'gen(t)st]",
"Делать прививку (получить)", "To be vaccinated 	[biː ' væksɪneɪtid]",
"Побочный эффект", "Side effect	[saɪd ɪ'fekt]",
"Вправлять вывих", "To set a bone 	[set ə bəun]",
"В аптеке", "At the chemist’s (Br.) / At the drugstore (Am.)	[ət ðə 'kemɪsts] / [ət ðə 'drʌgstɔː]",
"Лекарство от …", "	Medicine for …	['medɪsɪn fɔː]",
"Таблетки", "Pills 	[pilz]",
"Вата", "Cotton	['kɔt(ə)n]",
"Йод", "Iodine	['aɪədiːn]",
"Пластырь", "Plaster (br.) /band-aid(am.)	['plɑːstə] / ['bænd eɪd]",
"Аспирин", "Aspirin	['æsp(ə)rɪn]",
"Бинт", "Bandage	['bændɪʤ]",
"Обезболивающее средство", "Pain killer	[peɪn 'kɪlə]",
"Рецепт", "Prescription	[prɪs'krɪpʃ(ə)n]",
"Слабительное", "Laxative	['læksətɪv]",
"Лекарство для полоскания горла", "Throat gargle	[θrəut 'gɑːgl]",
"Дезинфицирующее", "Antiseptic	[ˌæntɪ'septɪk]",
"Обезболивающее", "Anaesthetic	[ˌænəs'θetɪk]",
"Медицинская помощь", "Medical aid	 ['medɪk(ə)l eɪd]",
"Поликлиника", "Medical center 	['medɪk(ə)l 'sentə]",
"Больница", "Hospital	['hɔspɪt(ə)l]",
"Скорая помощь", "Ambulance	['æmbjələn(t)s]",
"Пациент", "Patient 	['peɪʃ(ə)nt]",
"Врач", "Doctor	['dɔktə]",
"Лечь в больницу", "To go to hospital	[gəu tə 'hɔspɪt(ə)l]",
"Лежать в больнице", "To be in hospital	[biː ɪn 'hɔspɪt(ə)l]",
"Вызвать врача", "To call the doctor	[kɔːl ðə 'dɔktə]",
"Записаться на прием к врачу", "To make an appointment with a doctor	[meɪk ən ə'pɔɪntmənt wɪð ə 'dɔktə]",
"Фразы о здоровье", "'Health' phrases	 [ helθ freɪziz ]",
"Грех жаловаться", "Can’t complain	[kɑːnt kəm'pleɪn]",
"Испытывать стресс", "To be stressed out	[bi: strest aut]",
"Воплощение здоровья", "The picture of health	[ðə 'pɪkʧər əv 'helθ]",
"Снова встать на ноги", "To be back on one’s feet	[bi: bæk ɔn<one's>fi:t]",
"Сильная головная боль", "A splitting headache	[ə 'splɪtɪŋ 'hedeɪk]",
"Распространяться, ходить (о заболевании)", "To go round	[gəu raund]",
]

const food = [
"Фрукты", "Fruit	[fruːt]",
"Яблоко", "Apple	['æpl]",
"Лимон", "Lemon	['lemən]",
"Манго", "Mango	['mæŋgəu]",
"Лайм", "Lime	[laɪm]",
"Слива", "Plum	[plʌm]",
"Груша", "Pear	[peə]",
"Киви", "Kiwi	['kiːwiː]",
"Апельсин", "Orange	['ɔrɪnʤ]",
"Дыня", "Melon	['melən]",
"Банан", "Banana	[bə'nɑːnə]",
"Ягода", "Berry	['berɪ]",
"Вишня", "Cherry	['ʧerɪ]",
"Дыня", "Melon	['melən]",
"Смородина", "Currant	['kʌr(ə)nt]",
"Виноградина", "Grape	[greɪp]",
"Ананас", "Pineapple	['paɪnæpl]",
"Кокос", "Coconut	['kəukənʌt]",
"Гранат", "Pomegranate	['pɔmɪˌgrænɪt]",
"Абрикос", "Apricot	['eɪprɪkɔt]",
"Смородина", "Currant	['kʌr(ə)nt]",
"Малина", "Raspberry	['rɑːzb(ə)rɪ]",
"Клубника", "Strawberry	['strɔːb(ə)rɪ]",
"Мандарин", "Tangerine	[ˌtænʤ(ə)'riːn]",
"Арбуз", "Watermelon	['wɔːtəˌmelən]",
"Персик", "Peach	[piːʧ]",
"Папайя", "Papaya	[pə'paɪə]",
"Клюква", "Cranberry	['krænb(ə)rɪ]",
"Нектарин", "Nectarine	['nekt(ə)riːn]",
"Грейпфрут", "Grapefruit	['greɪpfruːt]",
"Ежевика", "Blackberry	['blækb(ə)rɪ]",
"Черника, голубика", "Blueberry	['bluːbərɪ]",
"Изюм", "Raisin	['reɪz(ə)n]",
"Финик", "Date	[deɪt]",
"Маракуя", "Passion fruit	['pæʃ(ə)n fru:t]",
"Овощи", "Vegetables	['veʤ(ə)təblz]",
"Картофель", "Potato	[pə'teɪtəu]",
"Свекла", "Beet	[biːt]",
"Капуста", "Cabbage	['kæbɪʤ]",
"Морковь", "Carrot	['kærət]",
"Боб, фасоль", "Bean	[biːn]",
"Чеснок", "Garlic	['gɑːlɪk]",
"Оливка", "Olive	['ɔlɪv]",
"Перец", "Pepper	['pepə]",
"Помидор", "Tomato	[tə'mɑːtəu]",
"Огурец", "Cucumber	['kjuːkʌmbə]",
"Баклажан", "Eggplant (am.) / aubergine(br.)	['egplɑːnt] / ['əubəʤiːn]",
"Гриб", "Mushroom	['mʌʃrum]",
"Репчатый лук", "Onion	['ʌnjən]",
"Авокадо", "Avocado	[ˌævə'kɑːdəu]",
"Зелень", "Greens	[gri:nz]",
"Редис", "Radish	['rædɪʃ]",
"Артишок", "Artichoke	['ɑːtɪʧəuk]",
"Спаржа", "Asparagus	[əs'pærəgəs]",
"Цветная капуста", "Cauliflower	['kɔlɪˌflauə]",
"Сельдерей", "Celery	['sel(ə)rɪ]",
"Имбирь", "Ginger	['ʤɪnʤə]",
"Салат-латук", "Lettuce	['letɪs]",
"Укроп", "Dill	[dɪl]",
"Петрушка", "Parsley	['pɑːslɪ]",
"Зеленый горошек (горошина)", "Pea	[piː]",
"Тыква", "Pumpkin	['pʌmpkɪn]",
"Шпинат", "Spinach	['spɪnɪʧ], [-ʤ]",
"Репа", "Turnip	['tɜːnɪp]",
"Кабачок", "Zucchini	[zu'kiːnɪ]",
"Мясо", "Meat	[mi:t]",
"Курица", "Chicken	['ʧɪkɪn]",
"Свинина", "Pork	[pɔːk]",
"Индейка", "Turkey	['tɜːkɪ]",
"Говядина", "Beef	[bi:f]",
"Баранина", "Mutton	['mʌt(ə)n]",
"Колбаса", "Sausage	['sɔsɪʤ]",
"Бекон", "Bacon	['beɪk(ə)n] ",
"Ветчина", "Ham	[hæm]",
"Сосиска", "A sausage	[ə 'sɔsɪʤ]",
"Молодая баранина, ягненок", "Lamb	[læm]",
"Телятина", "Veal	[vi:l]",
"Домашняя птица", "Poultry	['pəultrɪ] ",
"Фарш", "Minced meat	[mɪn(t)st mi:t]",
"Рыба", "Fish	[fɪʃ]",
"Тунец", "Tuna	['tjuːnə]",
"Лосось, семга", "Salmon	['sæmən]",
"Треска", "Cod	[kɔd]",
"Осетр", "Sturgeon	['stɜːʤ(ə)n]",
"Форель", "Trout	[traut]",
"Сельдь", "Herring	['herɪŋ]",
"Камбала", "Plaice	[pleɪs]",
"Пикша", "Haddock	['hædək]",
"Щука", "Pike	[paɪk]",
"Угорь", "Eel	[i:l]",
"Палтус", "Sole	[səul]",
"Окунь", "Bass	[bæs]",
"Морепродукты", "Seafood	[si: fu:d]",
"Икра", "Caviar	['kævɪɑː]",
"Краб", "Crab	[kræb]",
"Осьминог", "Octopus	['ɔktəpəs]",
"Мидия", "Mussel	['mʌs(ə)l]",
"Моллюск", "Clam	[klæm]",
"Устрица", "Oyster	['ɔɪstə]",
"Лобстер", "Lobster	['lɔbstə]",
"Креветка", "(большая)	Prawn	[prɔːn]",
"Креветка", "Shrimp	 [ʃrɪmp]",
"Кальмар", "Squid	[skwɪd]",
"Анчоус", "Anchovy	['ænʧəvɪ]",
"Крупы, зерновые", "Grains	[greɪnz]",
"Рис", "Rice	[raɪs]",
"Макароны", "Pasta	['pæstə]",
"Овсяная каша	", "Porridge	['pɔrɪʤ]",
"Лапша", "Noodle	['nuːdl]",
"Кукуруза", "Corn	[kɔːn]",
"Пшеница", "Wheat	[(h)wiːt]",
"Рожь", "Rye	[raɪ]",
"Греча", "Buckwheat	['bʌkwiːt]",
"Крупы, злаки", "Cereals	['sɪərɪəlz]",
"Овсяная крупа", "Oatmeal	['əutmiːl]",
"Манная крупа", "Semolina	[ˌsem(ə)'liːnə]",
"Молочные продукты", "Dairy	['deərɪ]",
"Сливочное масло", "Butter	['bʌtə]",
"Сыр", "Cheese	[ʧiːz]",
"Молоко", "Milk	[mɪlk]",
"Творог", "Cottage cheese	['kɔtɪʤ ʧiːz] ",
"Майонез", "Mayonnaise	[ˌmeɪə'neɪz]",
"Йогурт", "Yogurt	['jɔgət], ['jəu-], ['jɔgɜːt]",
"Сливки", "Cream	[kri:m]",
"Сметана", "Sour cream	['sauə kri:m]",
"Творог, свернувшееся молоко", "Curd	[kɜːd]",
"Мучные продукты", "Flour products	['flauə 'prɔdʌkts]",
"Кекс, пирожное, торт", " Cake	[keɪk]",
"Хлеб", " Bread	[bred]",
"Печенье", " Cookie = biscuit	['kukɪ] = ['bɪskɪt]",
"Блин, оладья", " Pancake	['pænkeɪk]",
"Пирог, пирожок", " Pie	[paɪ]",
"Мука", " Flour	['flauə]",
"Белый хлеб = пшеничный хлеб", " White bread = wheat bread	[(h)waɪt bred] = [(h)wi:t bred]",
"Черный хлеб = ржаной хлеб", " Black bread = rye bread	[blæk bred] = [raɪ bred]",
"Пирог (с фруктами, ягодами или вареньем), домашний торт", "	Tart	[tɑːt]",
"Пирожок с начинкой", " Pasty	['pæstɪ]",
"Кекс", " Muffin	['mʌfɪn]",
"Выпечка, мучные кондитерские изделия", " Pastry	['peɪstrɪ]",
"Тесто (густое)", " Dough	[dəu]",
"Тесто (жидкое)", "Batter	['bætə]",
"Сдобная булочка", " Bun	[bʌn]",
"Разное", "Miscellaneous	[ˌmɪs(ə)'leɪnɪəs]",
"Яйцо", "Egg	[eg]",
"Сахар", "Sugar	['ʃugə]",
"Подсолнечное масло", "Oil	[ɔɪl]",
"Шоколад", "Chocolate	['ʧɔklət]",
"Соль", "Salt	[sɔːlt]",
"Черный перец", "Black pepper	[blæk 'pepə]",
"Конфета", "Candy = sweet	['kændɪ] = [swi:t]",
"Варенье", "Jam	[ʤæm]",
"Джем, повидло", "Marmalade	['mɑːm(ə)leɪd]",
"Мед", "Honey	['hʌnɪ]",
"Специя, пряность", "Spice	[spaɪs]",
"Приправа", "Seasoning	['siːz(ə)nɪŋ]",
"Горчица", "Mustard	['mʌstəd]",
"Консервы", "Canned food = tinned food	[kændfu:d] = [tɪndfu:d]",
"Описание еды", "Describing food	[dɪ'skraɪbɪŋ fu:d]",
"Сладкий", "Sweet	[swiːt]",
"Соленый", "Salty	['sɔːltɪ]",
"Вкусный", "Delicious = tasty = yummy	[dɪ'lɪʃəs]=['teɪstɪ]=['jʌmɪ]",
"Свежий", "Fresh	[freʃ]",
"Не содержащий сахара", "Sugar-free	['ʃugəfri:]",
"Горячий; острый", "Hot	[hɔt]",
"Горький", "Bitter	['bɪtə]",
"Полезный	", "Healthy	['helθɪ]",
"Кислый", "Sour	['sauə]",
"Острый", "Spicy	['spaɪsɪ]",
"Маслянистый", "Oily	['ɔɪlɪ]",
"Сырой", "Raw	[rɔː]",
"Зрелый, спелый", "Ripe	[raɪp]",
"Неспелый", "Unripe	[ʌn'raɪp]",
"Гнилой, испорченный", "Rotten	['rɔt(ə)n]",
"Прокисший, тухлый", "Spoiled	[spɔɪld]",
"Жесткий", "Tough	[tʌf]",
"Мягкий", "Soft	[sɔft]",
"Черствый, несвежий", "Stale	[steɪl]",
"Нежный, тонкий (о вкусе)", "Delicate	['delɪkət]",
"Терпкий, вяжущий", "Acerbic	[ə'sɜːb(ɪk)]",
"Недоваренный", "Undercooked	['ʌndəkukt]",
"Переваренный", "Overcooked	['əuvəkukt]",
"Горький", "Bitter	['bɪtə]",
"Пресный, неострый, безвкусный", "Bland	[blænd]",
"Нежный, густой, сметанообразный", "Creamy	['kriːmɪ]",
"Хрустящий", "Crispy = crunchy	['krɪspɪ] = [krʌnʧi]",
"Пикантный, пряный", "Savoury	['seɪv(ə)rɪ]",
"Густой	", "Stodgy	['stɔʤɪ]",
"Безвкусный", "Tasteless	['teɪstləs]",
"Вредный, нездоровый", "Unhealthy	[ʌn'helθɪ]",
"Калорийный", "High-caloric	[haɪkə'lɔrɪk] ",
"Жирный, содержащий много жира", "Greasy = fatty	['griːsɪ] =  ['fætɪ]",
"Питательный", "Nutritious	[njuː'trɪʃəs]",
"Сытный", "Substantial	[səb'stæn(t)ʃ(ə)l]",
"Постный, содержащий мало жиров", "Lean	[li:n]",
"Непрожаренный, с кровью", "Rare	[reə]",
"Хорошо прожаренный", "Well-done	[ˌwel'dʌn]",
"Приготовление пищи", "Cooking	['kukɪŋ]",
"Смешивать", "To mix	[mɪks]",
"Резать", "To cut	[kʌt]",
"Варить", "To boil	[bɔɪl]",
"Жарить", "To fry	[fraɪ]",
"Охлаждать", "To cool	[ku:l]",
"Добавлять", "To add	[æd]",
"Печь", "To bake	[beɪk]",
"Жарить на рашпере", "To barbecue = to grill	['bɑːbɪkjuː] =  [grɪl]",
"Взбивать, отбивать", "To beat	[bi:t]",
"Подогревать", "To heat up = to warm up	[hi:tʌp] = [wɔːmʌp]",
"Резать на мелкие кусочки", "To chop	[ʧɔp]",
"Измельчать, толочь", "To crush	[krʌʃ]",
"Резать кубиками", "To dice	[daɪs]",
"Тереть на терке", "To grate	[greɪt]",
"Измерять", "To measure	['meʒə]",
"Отчищать", "To peel	[pi:l]",
"Наливать", "To pour	[pɔː]",
"Жарить в духовке/на огне", "To roast	[rəust] ",
"Взбалтывать", "To scramble	['skræmbl]",
"Варить на медленном огне", "To simmer	['sɪmə] ",
"Резать ломтиками", "To slice	[slaɪs]",
"Готовить на пару", "To steam	[sti:m]",
"Взвешивать", "To weigh	[weɪ]",
"Кухонная утварь и приспособления", "Kitchen utensils & devices	['kɪʧɪn juː'tens(ə)lz & dɪ'vaɪsiz]",
"Плита", "Cooker = stove	['kukə] = [stəuv]",
"Духовка", "Oven	['ʌv(ə)n]",
"Ложка", "Spoon	[spu:n]",
"Чашка", "Cup	[kʌp]",
"Тарелка", "Plate	[pleɪt]",
"Стакан, бокал", "Glass	[gla:s]",
"Чайник", "Kettle	['ketl]",
"Нож", "Knife	[naɪf]",
"Холодильник", "Fridge	[frɪʤ]",
"Банка", "Jar	[ʤɑː]",
"Миска", "Bowl	[bəul]",
"Кружка", "Mug	[mʌg]",
"Вилка", "Fork	[fɔːk] ",
"Чайная ложка", "Tea spoon	[ti: spu:n]",
"Кастрюля", "Pan = saucepan	[pæn] = ['sɔːspən] ",
"Сковородка", "Frying pan	['fraɪɪŋˌpæn]",
"Крышка", "Lid	[lɪd]",
"Терка", "Grater	['greɪtə]",
"Мясорубка", "Mincer = meat grinder	['mɪn(t)sə]=[mi:t 'graɪndə]",
"Дуршлаг", "Colander	['kʌləndə]",
"Скалка", "Rolling pin	['rəulɪŋˌpɪn]",
"Сито", "Sieve	[sɪv]",
"В ресторане", "At a restaurant	[ət ə 'restərɔnt]",
"Завтрак", "Breakfast	['brekfəst]",
"Обед", "Lunch	[lʌnʧ]",
"Ужин", "Dinner	['dɪnə]",
"Кафе", "Cafe	['kæfeɪ], [kæ'feɪ]",
"Десерт", "Dessert	[dɪ'zɜːt]",
"Официант", "Waiter	['weɪtə]",
"Шеф-повар", "Chef	[ʃef]",
"Заказ (ывать)", "(to) order	['ɔːdə]",
"Обслуживание", "Service	 ['sɜːvɪs] ",
"Счет", "Bill 	[bɪl] ",
"Чаевые", "Tips	[tɪps]",
"Меню", "Menu	['menjuː]",
"Напитки", "Beverages = drinks	['bevərɪʤiz] = [drɪŋks] ",
"Кухня национальная", "Cuisine	[kwɪ'ziːn]",
"Фирменное блюдо", "Speciality	[ˌspeʃɪ'ælətɪ]",
"Прием пищи, еда", "Meal	[mi:l]",
"Поздний завтрак (заменяющий первый и второй завтрак)", "Brunch	[brʌnʧ]",
"Меню на выбор", "A la carte menu 	[ˌala'kɑːt 'menjuː]",
"Блюда шведского стола", "Buffet	['bufeɪ]",
"Зарезервировать стол", "To book a table = to reserve a table	[buk ə 'teɪbl] / [rɪ'zɜːv ə 'teɪbl] ",
"Закуски", "Appetizers = starters = hors d'oeuvre	['æpɪtaɪzəz] = ['stɑːtəz] = [ˌɔː'dɜːv(rə)z]",
"Основное блюдо, горячее", "Main course	[meɪnkɔːs]",
"Блюдо, кушанье", "Dish	[dɪʃ] ",
"Алкогольный напиток", "Alcoholic beverage	[ælkə'hɔlɪk 'bevərɪʤ]",
"Безалкогольный напиток", "Non-alcoholic beverage	[ˌnɔnælkə'hɔlɪk 'bevərɪʤ]",
"Блюдо дня", "Special	['speʃ(ə)l]",
"Свеча", "Candle	['kændl]",
"Пакет, куда посетители ресторана могут положить оставшуюся пищу, чтобы взять домой", "	Doggie bag	['dɔgɪ bæg]"
]

let count = 0

let categChoose = null // переменная для получения имени класса по нажатию из списка категории в html
let concatWords = { // массив для получения всех переменных со словами. Это надо для оптимизации кода, т.е. мы будем перебирать массив и подставлять необходимую переменную в зависимости от выбранной пользователем категории, которая будет совпдать по имени класса категории
    personal, //название свойств совпадают с названиями переменных, которые мы подставляем в качестве значений этих свойств, поэтому мы не пишем например personal : personal
    character,
    profession,
    body,
    clothes,
    routine,
    home,
    city,
    shopping,
    travelling,
    health,
    food
    // abstract,
    // adjectives
}

// ------------------------------Боковое окно вывода слов----------------------------------------------------------

// Включаем и выключаем окно в котором отображаются карточки, которые были уже открыты
onOff.onclick = function () {
  outputWindow.classList.toggle('hidden')
}

// -------------------------------------Выбор категории из списка (боковой панели)----------------------------------

// ---Перебираем Категории и "слушаем" какую выбрано (на какой произошло событие). Когда определяем, тогда добавляем новый класс
// --- Счетчик ставим на 0 для того, чтобы при выборе новой категории слова начинались с первого слова в базе выбранной  категории
activeLi.map(function (elem) {
    elem.onclick = function (event) {
        categChoose = event.target.classList[1] // При нажатии мышкой узнал свойства объекта. В открытой консоли разработчика в свойствах "target" перешел в "classList". Посмотрел список классов. Под индексом 1 находиться наш неизменняемый класс в html/ Его мы и должны получить в переменную categChoose (см. ниже), которую мы будем подставлять в функцию листания слов при нажатии кнопок
        category.map(function (elem2) {
            elem2.classList.remove("current")
        })
        elem.classList.add("current")
        count = 0
        outputWindow.innerHTML = '' // очищаем окно вывода после каждого переключения категории
        word.innerHTML = 'Готов? <br> Тогда нажми кнопку "вперед" или "Auto" '
    }
})

// ---------------------------------Кнопка вперед ---------------------------------------------------------------

// --- При нажатии на кнопку "вперед" определяем какая категория активна (активность мы определии выше) и в зависимости от категории подставляем слова

btnNext.addEventListener('click', function () { // При нажатии на кнопку "Next" 
    activeLi.map(function (elem) { // перебираем все (li) с категориями в html 
        if (elem.classList.contains('current')) { // Если у выбранной категории есть класс с названием "current",
        if(count % 2 == 0){ // Делаем проверку. Если слово на русском (они идут по нечетным цифрам в массиве, т.е. 1, 3, 5...), тогда оно черного цвета, если четное , тогда синего цвета (английские слова)
          word.style.color = 'blue'}
          else {
            word.style.color = 'black'
          }
            for (key in concatWords) { // тогда перебираем массив "concatWords" с нашими переменными в которых храняться слова
                if (key === categChoose) { // И если название ключа в массиве "concatWords" совпадает с названием класса "concatWords"
                    if (count < concatWords[key].length) { //  тогда выводим слова, пока количество слов в масиве не закончиться
                        word.innerHTML = concatWords[key][count]; // здесь выводим на карточку в html (class="card")
                        outputWindow.innerHTML += concatWords[key][count] + '<br>'; //здесь выводим в боковое окно в html (class="outputWindow")
                        count++
                        if (count == 20 || count == 40 || count == 60 || count == 80 || count == 100 || count == 120 || count == 140 || count == 160 || count == 180 || count == 200 || count == 220 || count == 240 || count == 260 || count == 280 || count == 300 || count == 320) {
                            outputWindow.innerHTML = '' // Делаем проверку. Если окно вывода слов, которые были уже открыты, набрало 10 карточек (с двух сторон получается 20), т.е индекс (count) равен 20, 40 ..., тогда мы его отчищаем
                        }
                    }
                }
            }
        }
    })
})

// ---------------------------------------------------Кнопка назад -------------------------------------------

btnPrew.onclick = function () {
  activeLi.map(function (elem) {
    if (count == 20 || count == 40 || count == 60 || count == 80 || count == 100 || count == 120 || count == 140 || count == 160 || count == 180 || count == 200 || count == 220 || count == 240 || count == 260 || count == 280 || count == 300 || count == 320) {
      outputWindow.innerHTML = ''
    } 
    if(count % 2 == 0){ 
      word.style.color = 'blue'}
      else {
        word.style.color = 'black'
      }
    if(count < 1){ // Если слова закончились, тогда выводим ничего не выводим (если этого не сделать будет выводиться undefind)
      outputWindow.innerHTML = ""
      word.innerHTML = ""
      count = 0
    }
    if (elem.classList.contains('current')) {
      for (key in concatWords) { 
      if (key === categChoose) { 
                           count--// счетчик вверху, чтоб не было лишнего шага, потому что если его поставить ниже, после проделывания операции, тогда будет добавляться допалнительный шаг вперед, т.е. будет в outputWindow.innerHTML добавляться новое слово, которое не отображается в word.innerHTML (карточке))
            word.innerHTML = concatWords[key][count - 1]
            outputWindow.innerHTML += concatWords[key][count] + '<br>'
    
  }}}
}
  )}

// ---------------------------------Автоматическое проигрывание слов------------------------------------

let interval // Переменная созданная для того, чтоб можно было прервать выполнение метода setInterval

auto.onclick = function auto() { // запускаем выполнение автомотического проигрывания слов
    
  activeLi.map(function (elem) {
    if (elem.classList.contains('current')) {
            interval = setInterval(function () {
              if(count % 2 == 0){ 
                word.style.color = 'blue'}
                else { word.style.color = 'black'}
        for (key in concatWords) { // тогда перебираем массив "concatWords" с нашими переменными в которых храняться слова
                if (key === categChoose) {
        if (count < concatWords[key].length) {
          word.innerHTML = concatWords[key][count];
          outputWindow.innerHTML += concatWords[key][count] + '<br>';
          count++
          if (count == 20 || count == 40 || count == 60 || count == 80 || count == 100 || count == 120 || count == 140 || count == 160 || count == 180 || count == 200 || count == 220 || count == 240 || count == 260 || count == 280 || count == 300 || count == 320) {
            outputWindow.innerHTML = ''
          } // Делаем проверку. Если окно вывода слов, которые были уже открыты, набрало 10 карточек (с двух сторон получается 20), т.е индекс (count) равен 20, 40 ..., тогда мы его отчищаем
        }}}
      }, 2500)
    }
  })
}

stopAuto.onclick = () => {
  clearTimeout(interval) //Прерываем выполнение запущеного автомотического проигрывания слов
}

// ---------------------Заканчиывается код по автоматическому проигрыванию слов ------------------------

// ---------------------------Кнопка "случайная категория" ------------

randomWord.addEventListener("click", function () {
      activeLi.map(function(elem){ // Перед выбором случайной категории очищаем (удаляем класс "current")
      elem.classList.remove("current") 
      })
      let x = [Math.floor(Math.random()* activeLi.length)] // Получаем рандомное (случайное) число, которое не превышает длину массива  (количество категорий (li))
      activeLi[x].classList.add("current") // подставляем случайный индекс и получаем случайную  категорию
      count = 0
      outputWindow.innerHTML = '' // очищаем окно вывода после каждого переключения категории
      word.innerHTML = 'Готов? <br> Тогда нажми кнопку "вперед" или "Auto" '
   }
)

// -------------------------Сделать Избранное куда добавлять свои слова-------------






// activeLi.map(function (elem) {
//   elem.onclick = function (event) {
//       categChoose = event.target.classList[1] // При нажатии мышкой узнал свойства объекта. В открытой консоли разработчика в свойствах "target" перешел в "classList". Посмотрел список классов. Под индексом 1 находиться наш неизменняемый класс в html/ Его мы и должны получить в переменную categChoose (см. ниже), которую мы будем подставлять в функцию листания слов при нажатии кнопок
//       category.map(function (elem2) {
//           elem2.classList.remove("current")
//       })
//       elem.classList.add("current")
//       count = 0
//       outputWindow.innerHTML = '' // очищаем окно вывода после каждого переключения категории
//       word.innerHTML = 'Готов? <br> Тогда нажми кнопку "вперед" или "Auto" '
//   }
// })
// ---------------------------Заканчивается кнопка случайных слов---------------------------------------------------


//Это к программе не относится 
// const a = [["Управление",	"Management	['mænɪʤmənt]"],[ "Президент", "President	['prezɪd(ə)nt]"]]

// console.log (a)



// // Object.fromEntries(a);
// console.log(Object.fromEntries(a))